### ISSUE TITLE
"Unable to download from ..." SSL Certificat Error

### ISSUE THREAD

**Issue by mosdevly** [rubygems/rubygems#1050]
The error is as follows:

https://gist.github.com/Protosac/a5b86b0461940d36e298

```
Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/specs.4.8.gz)
```

I saw some old posts about this but they didn't offer any solutions, since it seemed the error isn't on the user side. Any help appreciated.

**Comment by ivanhoinacki** [comment]
I logged just to say I love you hahaha :dancer:

**Comment by gigaimage** [comment]
On Win 7 machine:
C:\>ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]

C:\>gem --version
2.2.2

C:\>gem update bundler
Updating installed gems
Nothing to update

C:\>gem install rails 
ERROR:  Could not find a valid gem 'rails' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/latest_specs.4.8.gz)

**Comment by gigaimage** [comment]
I tried updating local gem... but failing on cert error 

C:\>gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

**Comment by dwradcliffe** [comment]
You need to update your rubygems version. See:
https://gist.github.com/luislavena/f064211759ee0f806c88

---
David Radcliffe
radcliffe.david@gmail.com
dwradcliffe.com

**Comment by gigaimage** [comment]
@dwradcliffe  Thanks!

**Comment by gmangalo** [comment]
Hi,

Im seeing the same issue without the SSL error on my OS X 10.9.5

C:~ gmangalo$ gem update --system
Latest version currently installed. Aborting.
C:~ gmangalo$ gem -v
2.0.14
C:~ gmangalo$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
C:~ gmangalo$ ruby -ropenssl -e 'p OpenSSL::OPENSSL_VERSION'
"OpenSSL 0.9.8y 5 Feb 2013"
C:~ gmangalo$ gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)

Tried adding --source parameter but no avail

C:~ gmangalo$ gem install bundler -r --source http://rubygems.org
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)
          Unable to download data from http://rubygems.org/ - no such name (http://rubygems.org/latest_specs.4.8.gz)

**Comment by shyakaster** [comment]
Am having the same certificate issue on windows 8.1.

**Comment by lichtamberg** [comment]
me 2

**Comment by drbrain** [comment]
@gmangalo you appear to be unable to resolve DNS names properly.

@shyakaster, @lichtamberg check the [guide for the certificate error](http://guides.rubygems.org/ssl-certificate-update)

**Comment by ber855** [comment]
I'm trying to implement the recommended solution at http://guides.rubygems.org/ssl-certificate-update/ but I don't seem to be able to update rubygems on Windows7 with Ruby21-x64 installed.

````
 C:\>ruby -v
 ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]
 
 C:\>gem --version
 2.2.2
 
 C:\>gem install --local C:\rubygems-update-2.2.3.gem
 Successfully installed rubygems-update-2.2.3
 Parsing documentation for rubygems-update-2.2.3
 Done installing documentation for rubygems-update after 0 seconds
 1 gem installed
 
 C:\>update_rubygems --no-ri --no-rdoc
 
 C:\>gem --version
 2.2.2
 
 C:\>update_rubygems --help
 rubygems_update [options]
 
 This will install the latest version of RubyGems.
 
        --version=X.Y   Update rubygems from the X.Y version.
 
 C:\>update_rubygems --no-ri --no-rdoc --version=2.2.2
 C:/Program Files/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubygems-update-2.2.3/bin/update_rubygems:20:in `exec': No such file or directory - "C:/Program Files/Ruby21-x64/bin/ruby.exe" (Errno::ENOENT)
        from C:/Program Files/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubygems-update-2.2.3/bin/update_rubygems:20:in `<top (required)>'
        from C:/Program Files/Ruby21-x64/bin/update_rubygems:23:in `load'
        from C:/Program Files/Ruby21-x64/bin/update_rubygems:23:in `\<main\>'
 
 C:\>dir "C:\Program Files\Ruby21-x64\bin\ruby.exe"
  Volume in drive C is OSDisk
  Volume Serial Number is 0870-8892
 
  Directory of C:\Program Files\Ruby21-x64\bin
 
 11/15/2014  09:33 PM           148,828 ruby.exe
                1 File(s)        148,828 bytes
                0 Dir(s)  373,562,097,664 bytes free


 C:\>gem --version
 2.2.2
 ````

And then as you would expect:

````
 C:\>gem update --system
 ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
     SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed  (https://api.rubygems.org/specs.4.8.gz)
````

Copying the new certificate into the ssl_certs directory manually doesn't appear to work either.  Any suggestion you can offer would be greatly appreciated.  I'm new to Ruby, and am basically just trying to follow instructions created by a team member who has more experience with Ruby but is similarly stumped by this issue.

**Comment by drbrain** [comment]
@ber855 RubyGems and gems are not known to work well with directories containing spaces.  Does it work when using a space-free directory?

**Comment by ber855** [comment]
Unfortunately, I'm in a locked-down environment and can't run exe's from outside the "Program Files" or "Program Files (x86)" directory.  Gems does seem to run, though.  Could that be the source of the "certificate verify failed" error?

At the suggestion of a teammate, I tried dropping back to version 2.0.0p643, which somewhat unexpectedly came with Gems 2.4.6.  Unfortunately, I'm still getting the same error.

````
C:\git\tdameritrade-veo\UI>where gem
C:\Program Files\Ruby200-x64\bin\gem
C:\Program Files\Ruby200-x64\bin\gem.bat

C:\git\tdameritrade-veo\UI>ruby -v
ruby 2.0.0p643 (2015-02-25) [x64-mingw32]

C:\git\tdameritrade-veo\UI>gem --version
2.4.6

C:\git\tdameritrade-veo\UI>gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
````

The same teammate now suggests I drop back to version 1.9.3p551...  :-/

**Comment by ber855** [comment]
Dropping back to version 1.9.3p551 did not help.

````
C:\>where gem
C:\Program Files\Ruby193\bin\gem
C:\Program Files\Ruby193\bin\gem.bat

C:\>ruby -v
ruby 1.9.3p551 (2014-11-13) [i386-mingw32]

C:\>gem --version
1.8.29

C:\>gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/latest_specs.4.8.gz)

C:\>gem install --local C:\rubygems-update-1.8.30.gem
Successfully installed rubygems-update-1.8.30
1 gem installed
Installing ri documentation for rubygems-update-1.8.30...
Installing RDoc documentation for rubygems-update-1.8.30...

C:\>update_rubygems --no-ri --no-rdoc

C:\>gem --version
1.8.29

C:\>update_rubygems --help
rubygems_update [options]

This will install the latest version of RubyGems.

        --version=X.Y   Update rubygems from the X.Y version.

C:\>update_rubygems --no-ri --no-rdoc --version=1.8.29
C:/Program Files/Ruby193/lib/ruby/gems/1.9.1/gems/rubygems-update-1.8.30/bin/upd
ate_rubygems:20:in `exec': No such file or directory - "C:/Program Files/Ruby193
/bin/ruby.exe" (Errno::ENOENT)
        from C:/Program Files/Ruby193/lib/ruby/gems/1.9.1/gems/rubygems-update-1.8.30/bin/update_rubygems:20:in `<top (required)>'
        from C:/Program Files/Ruby193/bin/update_rubygems:23:in `load'
        from C:/Program Files/Ruby193/bin/update_rubygems:23:in `<main>'

C:\>gem --version
1.8.29
````

And then, as you would expect.

````
C:\>gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/latest_specs.4.8.gz)
````

Could that space in the path to the ruby or gem exe be preventing me from upgrading the Gems version?  If so, I might be able to ask for a temporary exception from the security policy.

**Comment by socratesmedina** [comment]
I am getting the same error, too:


C:\Sites>gem update bundler
Updating installed gems
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

**Comment by silentbinary** [comment]
I am in the same position, tried every permutation of GEMS / Ruby and to put it mildly its totally broken.  Is there an official statement regarding this and when it will be resolved.

**Comment by silentbinary** [comment]
C:\WINDOWS\system32>gem install rack --clear-sources --verbose --source https://staging.rubygems.org -v 1.5.2
HEAD https://staging.rubygems.org/api/v1/dependencies
200 OK
GET https://staging.rubygems.org/api/v1/dependencies?gems=rack
200 OK
GET https://staging.rubygems.org/quick/Marshal.4.8/rack-1.5.2.gemspec.rz
302 Moved Temporarily
GET https://rubygems-staging.global.ssl.fastly.net/quick/Marshal.4.8/rack-1.5.2.gemspec.rz
404 Not Found
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://rubygems-staging.global.ssl.fastly.net/quick/Marshal.4.8/rack-1.5.2.gemspec.rz)

C:\WINDOWS\system32>

**Comment by dwradcliffe** [comment]
@silentbinary Why are you using staging? The full set of gems is not available on staging, and it should not be used.

**Comment by silentbinary** [comment]
My Ruby knowledge is zero, I am just trying to follow the recommended fix.

On Thu, Sep 24, 2015 at 3:33 PM, David Radcliffe <notifications@github.com>
wrote:

> @silentbinary <https://github.com/silentbinary> Why are you using
> staging? The full set of gems is not available on staging, and it should
> not be used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubygems/rubygems/issues/1050#issuecomment-142947166>.
>



-- 

Land Line |  0208 1234 409 |   Mobile | 07779256256

Conference Call | 0844737373 | Pin 590342

Email | Skype | Gareth.Davies@SilentBinary.co
<Gareth.Davies@SilentBinary.com>.uk

LinkedIn | https://www.linkedin.com/in/alwaysdelivers




SilentBinary.Co.Uk accepts no liability for the content of this email, or
for the consequences of any actions taken on the basis of the information
provided, unless that information is subsequently confirmed in writing.

**Comment by dwradcliffe** [comment]
This is an old issue that is resolved. The mention of staging above was to test a new SSL cert before it was rolled out to production.

**Comment by silentbinary** [comment]
I still have the same issue on Windows.

<img width="1100" alt="shot 2" src="https://cloud.githubusercontent.com/assets/8680631/10077268/794e8924-62d7-11e5-88f5-58ccf1137b4d.png">
<img width="1216" alt="shot1 1" src="https://cloud.githubusercontent.com/assets/8680631/10077275/80e6acca-62d7-11e5-8bbf-3e5ec00fc5c7.png">

**Comment by dwradcliffe** [comment]
@silentbinary Looks like your issue is with the softlayer api, not the rubygems api. I'm guessing their HTTPS settings or their certificate are not compatible with windows. You may need to manually install their certificate or something like that.

**Comment by silentbinary** [comment]
going to try on Linux tmrw

**Comment by lengerfulluse** [comment]
Got the same issue. Currently use the insecure http instead of https as a workaround. 
    
    gem source -a http://rubygems.org/

**Comment by silentbinary** [comment]
I gave up on Windows put have it installed on Ubuntu and it works a treat.

**Comment by silentbinary** [comment]
I gave up with Windows and have it running on Ubuntu with no issues.

On Tue, Dec 1, 2015 at 1:28 PM, Wei Heng <notifications@github.com> wrote:

> Got the same issue. Currently use the insecure http instead of https as a
> workaround.
>
> gem source -a http://rubygems.org/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubygems/rubygems/issues/1050#issuecomment-160968459>.
>



-- 

Land Line |  0208 1234 409 |   Mobile | 07779256256

Conference Call | 0844737373 | Pin 590342

Email | Skype | Gareth.Davies@SilentBinary.co
<Gareth.Davies@SilentBinary.com>.uk

LinkedIn | https://www.linkedin.com/in/alwaysdelivers


SilentBinary.Co.Uk <http://silentbinary.co.uk/> accepts no liability for
the content of this email, or for the consequences of any actions taken on
the basis of the information provided, unless that information is
subsequently confirmed in writing.


PGP Key :
https://keyserver.pgp.com/vkd/DownloadKey.event?keyid=0x4F65FA23BE932249

OTR Key : F9344886 B2DC0DE9 A9F4FD94 F8297A6A 71FFA711

**Comment by thovo** [comment]
I got the same issue on my Windows 7
``
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol (https://api.rubygems.org/specs.4.8.gz)
``
I think it happened because I am using a company's computer that usualy followed some security policy check of company. I didn't meet this issue with my own laptop. Does someone have any idea to fix it completely?
I tried to use @lengerfulluse command to install gem and it works except some last errors but at least it installed the gem.

**Comment by silentbinary** [comment]
I have up and just spun up a linux desktop and had no issue installing.



Kindest Regards

Gareth.


Mobile | 07779256256

Conference Call | 0844737373 | Pin 590342

Email | Skype | Gareth.Davies@SilentBinary.co
<Gareth.Davies@SilentBinary.com>.uk

LinkedIn | https://www.linkedin.com/in/alwaysdelivers


SilentBinary.co.uk <http://silentbinary.co.uk/> accepts no liability for
the content of this email, or for the consequences of any actions taken on
the basis of the information provided, unless that information is
subsequently confirmed in writing.


PGP Key :
https://keyserver.pgp.com/vkd/DownloadKey.event?keyid=0x4F65FA23BE932249

OTR Key : F9344886 B2DC0DE9 A9F4FD94 F8297A6A 71FFA711

**Comment by dwradcliffe** [comment]
The original problem from this issue has been resolved. If you're still experiencing problems that seem related, open a help ticket or a new issue. Thanks!
