### ISSUE TITLE
getting "Gem::Package::PathError: installing into parent path" when building with rubygems ~> 2.5

### ISSUE THREAD

**Issue by elia** [rubygems/rubygems#1448]
_original issue: https://github.com/opal/opal/issues/1282_

When the gem is built with rubygems 2.5 (tested both 2.5.0 and 2.5.1) this error appears at install-time:

```
Gem::Package::PathError: installing into parent path /Users/jacobevelyn/.gem/ruby/2.3.0/gems/js-yaml/bin/js-yaml.js of /Users/jacobevelyn/.gem/ruby/2.3.0/gems/opal-0.9.1 is not allowed
```

Apparently this has to do with symlinks not properly expanded, the repo contains the following symlinks:

```
$ find . -type l
./stdlib/nodejs/node_modules/.bin/js-yaml
./stdlib/nodejs/node_modules/js-yaml/node_modules/.bin/esparse
./stdlib/nodejs/node_modules/js-yaml/node_modules/.bin/esvalidate
$ ll ./stdlib/nodejs/node_modules/.bin/js-yaml
lrwxr-xr-x  1 elia  staff    25B Oct 10 00:31 ./stdlib/nodejs/node_modules/.bin/js-yaml -> ../js-yaml/bin/js-yaml.js
```
Not sure who's right here, the symlink appears to consider the relative path from it's dirname, while rubygems calculates it from the gem's rootdir.

Even if rubygems' interpretation was right I think moving the error to build-time would be helpful.

I think that #1209 is the PR that introduced support for symlinks. cc @segiddins

**Comment by segiddins** [comment]
Thanks! I'll look into this sometime early next week.

**Comment by pedrocunha** [comment]
@segiddins any updates on this?

**Comment by segiddins** [comment]
Nope, not yet.

**Comment by pedrocunha** [comment]
As Elia as pointed out in the link above, and whoever comes across this, the only solution for now is to compile gems under ruby 2.2

**Comment by fuminori-ido** [comment]
I'm facing the same issue on my gem (edgarj) which has some local symlinks so that thank you for fixing this!  This fix seems not be released yet. When and which version (maybe 2.5.2?) is this fix released?

**Comment by segiddins** [comment]
@fuminori-ido the fix landed on master two days ago, it hasn't been released yet.

**Comment by sunaku** [comment]
:+1: I eagerly await the release containing this fix. :bow:

**Comment by indirect** [comment]
We are hoping to release a new version with this fix within the next few days.

**Comment by ioquatix** [comment]
I am having this problem too, it looks like the symlink is not being installed correctly.

**Comment by indirect** [comment]
This should be fixed in RubyGems 2.5.2.

**Comment by elia** [comment]
Thanks!

**Comment by ioquatix** [comment]
How do you update to RubyGems 2.5.2?

**Comment by ioquatix** [comment]
Oh, found it:

    gem update --system

**Comment by SamSaffron** [comment]
@indirect this is still broke to some degree of broke.... 

I installed latest rubygems on my 2.3.1 ruby here, built message_bus, it installs fine on latest rubygems, but does not install properly on older version of ruby. 

```
Gem::Package::PathError: installing into parent path /var/www/discourse/bundle/ruby/assets/message-bus-ajax.js of /var/www/discourse/bundle/ruby/2.2.0/gems/message_bus-2.0.0.beta.10 is not allowed
An error occurred while installing message_bus (2.0.0.beta.10), and Bundler
cannot continue.
Make sure that `gem install message_bus -v '2.0.0.beta.10'` succeeds before
```

**Comment by hsbt** [comment]
We addressed this issue on our tracker. ref https://bugs.ruby-lang.org/issues/12326

It will be fix at Ruby 2.3.2

**Comment by SamSaffron** [comment]
@hsbt thank you! but I feel the upgrade of rubygems is not enough, there is an underlying bug that is not fixed, something is broken about the packages latest rubygems is making. 

Try:

```
gem install message_bus -v '2.0.0.beta.10'
```

Install works fine in 2.3.1 (with latest rubygems) but is broken in older versions of ruby, the gem was assembled on latest rubygems. 

Only workaround I found was to build my gem on earlier versions of Ruby.

**Comment by nagachika** [comment]
I upgraded bundled rubygems to 2.5.2 on ruby 2.3 stable branch at https://github.com/ruby/ruby/commit/996b1bfa95347e5171c3f7ab32b6740656ed7a8b

**Comment by SamSaffron** [comment]
since this is still happening, I decided to stop thinking about this problem per:

https://github.com/SamSaffron/message_bus/commit/fd89e7df1e78d92f6de416506bf7cfdd733732e8
