### ISSUE TITLE
"Array values in the parameter are deprecated" warning not enough helpful ?

### ISSUE THREAD

**Issue by benoittgt** [rubygems/rubygems#1551]
Hello

My current problem is when I'm running my rails server (rails console, rails server) I get the warning added by @tenderlove in https://github.com/rubygems/rubygems/commit/a6b69e94232166dda441bbb69b64cf90562eebfd . The problem is the answer doesn't help me a lot to fix it. I get
```
Array values in the parameter are deprecated. Please use a String or nil.
An Array was passed in from bin/rails:3:in `load'
```

How can I get more infos to be able to fix this warning?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
2.6.2
$ rails --version
Rails 4.2.5.2
```

**Comment by tonyjleal** [comment]
I have the same problem 
Here are my current environment details:
```
$ gem env version
2.6.2
$ rails --version
Rails 4.2.1
```

**Comment by cstump** [comment]
I started seeing this yesterday after upgrading my **Rails 4.2.6** app to **Ruby 2.3.0** via [the official Ruby Docker image](https://hub.docker.com/_/ruby/) (ruby:2.3.0-slim). **Rubygems v2.6.2**.

**Comment by haggen** [comment]
Fixed by applying the same `join` you see [here](https://github.com/rubygems/rubygems/commit/a6b69e94232166dda441bbb69b64cf90562eebfd#diff-e2bd4eb9bbb8b25862825c636e55bd6dR367) to the line 11 in `bin/spring`:

```ruby
Gem.paths = { 'GEM_PATH' => [Bundler.bundle_path.to_s, *Gem.path].uniq.join(File::PATH_SEPARATOR) }
```

**Comment by benoittgt** [comment]
Thanks @haggen. That also fixed my issue.

**Comment by kathyonu** [comment]
Thank You @haggen Your line lights our app right up. I ran into this on the `rails -v` command. The Lovely error message led me right here on a search. Running 4.2.5.1 on 2.3.0p0

**Comment by conf** [comment]
If you came to this issue by googling the error specified in the description of this issue, you should know that it has already been fixed in `spring-1.6.4` and all you need to do is to update to latest `spring` and regenerate binstubs, like this:
```bash
$ bundle update spring && bundle exec spring binstub --remove --all && bundle exec spring binstub --all
```

**Comment by kirantpatil** [comment]
I am still getting it in rails 4.2.8 and ruby 2.4.1-x as below.

$ rails s
Array values in the parameter to `Gem.paths=` are deprecated.
Please use a String or nil.
An Array ({"GEM_PATH"=>["/home/fabritronix/.rvm/gems/ruby-2.4.1", "/home/fabritronix/.rvm/gems/ruby-2.4.1@global"]}) was passed in from bin/rails:3:in `load'
=> Booting Puma
=> Rails 4.2.8 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop

**Comment by brendon** [comment]
@NeoElit, check your `bin/rails` file in your application directory. You'll likely find that array on line 3.
