### ISSUE TITLE
Could it be that there are still issues with certificates?

### ISSUE THREAD

**Issue by jaragones** [rubygems/rubygems#1765]
I'm trying to do: 

jordi@Jordis-MacBook-Pro:~/Development/application$ sudo gem update
Password:
Updating installed gems
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

I've read that it should be fixed but is not working for me. Any clues?

**Comment by oldwit** [comment]
The same problem.
I did what is described http://guides.rubygems.org/ssl-certificate-update/
in MANUAL SOLUTION TO SSL ISSUE section but wan't help.

**Comment by duckinator** [comment]
Hi! Can you two provide the output of `gem env`, please? Thanks!

**Comment by jaragones** [comment]
I already tried to update before posting issue but didn't work. Here is the sequence, let see if we can figure out the issue :)

$ gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 2.2.2 (2015-04-13 patchlevel 95) [x86_64-darwin14]
  - INSTALLATION DIRECTORY: /Users/jordi/.rvm/gems/ruby-2.2.2
  - RUBY EXECUTABLE: /Users/jordi/.rvm/rubies/ruby-2.2.2/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/jordi/.rvm/gems/ruby-2.2.2/bin
  - SPEC CACHE DIRECTORY: /Users/jordi/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/jordi/.rvm/rubies/ruby-2.2.2/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-14
  - GEM PATHS:
     - /Users/jordi/.rvm/gems/ruby-2.2.2
     - /Users/jordi/.rvm/gems/ruby-2.2.2@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/jordi/.rvm/gems/ruby-2.2.2/bin
     - /Users/jordi/.rvm/gems/ruby-2.2.2@global/bin
     - /Users/jordi/.rvm/rubies/ruby-2.2.2/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/jordi/.rvm/bin

**Comment by luislavena** [comment]
Please download the `.gem` file and install as indicated in the guides section:

http://guides.rubygems.org/ssl-certificate-update/#installing-using-update-packages

Instructions use Windows drive/paths but should be similar for any other platform.

--

Users with old versions of RubyGems cannot run `gem update --system` (chicken an egg issue).

Hope that helps.

**Comment by oldwit** [comment]
It looks like problem is solved.
I've installed ruby 2.3.1 via rvm and set it as default current. 
Now I'm able to install gems from via https.

**Comment by jaragones** [comment]
Hi @luislavena, I tried and it didn't work neither... I also tried to do a manual installation with no luck... 

Sequence:
$ gem install --local Downloads/rubygems-update-2.6.7.gem 
Successfully installed rubygems-update-2.6.7
Parsing documentation for rubygems-update-2.6.7
Installing ri documentation for rubygems-update-2.6.7
Done installing documentation for rubygems-update after 29 seconds
1 gem installed

$ update_rubygems --no-ri --no-rdoc
RubyGems 2.6.7 installed

$ gem --version
2.6.7

$ gem update
Updating installed gems
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

$ gem uninstall rubygems-update-2.6.7



With the manual guide:

My certs look like this:

<img width="378" alt="screen shot 2016-11-03 at 9 53 35 am" src="https://cloud.githubusercontent.com/assets/2186315/19960169/67168838-a1ab-11e6-8398-3ef46f210f5a.png">

Notice, that I copied new GlobalSignRootCA.pem in directory. Should I do something to tell gem to "read" this file? Or should it be automatic?

**Comment by monteslu** [comment]
Same problem as @jaragones here.  Followed both sets of instructions at http://guides.rubygems.org/ssl-certificate-update and still getting the SSL problem.   The GlobalSignRootCA.pem  wasn't something in the directory before.  Is the naming correct?

**Comment by jaragones** [comment]
I couldn't make it work and i couldn't spend more time trying to fix it. I moved (temporally) to carthage (if it helps).

**Comment by drbrain** [comment]
Please try RubyGems 2.6.8, it has better diagnostics of SSL issues which will allow us to give you better guidance.

**Comment by jaragones** [comment]
$ gem --version
2.6.8

$ gem update
Updating installed gems
ERROR:  SSL verification error at depth 2: certificate has expired (10)
ERROR:  Certificate /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA expired at 2014-01-28T12:00:00Z
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)


These certificates are on my end or server side?

**Comment by drbrain** [comment]
This is an expired CA certificate on your end.  Please see these [instructions for removing the expired GlobalSign CA certificate](https://github.com/Homebrew/legacy-homebrew/issues/32251).

**Comment by monteslu** [comment]
This was showing the expired cert: `security find-certificate -a -p -c "GlobalSign Root CA"  /System/Library/Keychains/SystemRootCertificates.keychain`

So I followed the thread and then ran: ```sudo security delete-certificate -Z 2F173F7DE99667AFA57AF80AA2D1B12FAC830338 /System/Library/Keychains/SystemRootCertificates.keychain
brew postinstall openssl```

Then the first command shows the expired cert is gone now.

However, I'm still getting this trying to use gem 2.6.8:

```
ERROR:  SSL verification error at depth 2: certificate has expired (10)
ERROR:  Certificate /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA expired at 2014-01-28T12:00:00Z
ERROR:  SSL verification error at depth 2: certificate has expired (10)
ERROR:  Certificate /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA expired at 2014-01-28T12:00:00Z
ERROR:  SSL verification error at depth 2: certificate has expired (10)
ERROR:  Certificate /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA expired at 2014-01-28T12:00:00Z
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
ERROR:  SSL verification error at depth 2: certificate has expired (10)
ERROR:  Certificate /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA expired at 2014-01-28T12:00:00Z
```

**Comment by jaragones** [comment]
After following the link that @drbrain pointed looks that I only needed to run <brew install openssl> to make it work! 

Thanks for your help!

**Comment by monteslu** [comment]
This is still broken for me.  with or without brew's openssl.  No idea where the bad cert is being picked up from.

**Comment by jaragones** [comment]
Have you try to run doctor.rb from link above? it will report if you are missing cert in the directory and it will tell you its location.

**Comment by monteslu** [comment]
Thanks, @jaragones I missed the line about doctor.rb

Ok, working now.  For posterity on OSX Yosmite:

This showed that /etc/openssl was empty:
```
ruby doctor.rb rubygems.org
/Users/monteslu/.rvm/rubies/ruby-2.2.4/bin/ruby (2.2.4-p230)
OpenSSL 1.0.1j 15 Oct 2014: /etc/openssl
SSL_CERT_DIR=""
SSL_CERT_FILE=""

HEAD https://rubygems.org:443
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

The server presented a certificate that could not be verified:
  subject: /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
  issuer: /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
  error code 10: certificate has expired
```

This fixed it:

`sudo rvm osx-ssl-certs update all`

**Comment by matthewferguson** [comment]
You can run brew postinstall openssl to regen cert.pem without reinstalling all of openssl.
