### ISSUE TITLE
Cause found of: gem update --system fails with 'undefined method 'version' for nil:NilClass'.

### ISSUE THREAD

**Issue by sleekweasel** [rubygems/rubygems#1803]
I'm having a problem and would like to suggest a feature.

Feature:  I notice 'gem env' doesn't bother telling you RUBYOPT - seems you should add that.

Problem: My current problem is gem update --system fails with 'undefined method 'version' for nil:NilClass'.

This issue is related to the command line `gem`

> $ gem update --system
> Updating rubygems-update
> Successfully installed rubygems-update-2.6.8
> Parsing documentation for rubygems-update-2.6.8
> Done installing documentation for rubygems-update after 0 seconds
> Parsing documentation for rubygems-update-2.6.8
> Done installing documentation for rubygems-update after 0 seconds
> ERROR:  While executing gem ... (NoMethodError)
>     undefined method `version' for nil:NilClass
> 

I got this error, and ran a loop gradually setting the environment variables and trying the update each time to see which one triggered it. Turned out that

    export RUBYOPT=-rbundler/setup

was the offender: reset that, and gem update --system worked for me, even with the rest of my environment unchanged.

Quite why that's causing a problem, I have no idea: I don't set it myself - I guess RVM does that.

Here's my 'gem env' and some judicious greppings of 'env'.

set|grep RUBY
MY_RUBY_HOME=/Users/qa/.rvm/rubies/ruby-2.1.5
RUBYLIB=/Users/qa/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.13.6/lib
RUBYOPT=-rbundler/setup
RUBY_VERSION=ruby-2.1.5

set|grep GEM
BUNDLE_GEMFILE=/Users/qa/buildAgent/work/b9338fe8b12e747b/Gemfile
GEM_HOME=/Users/qa/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0
GEM_PATH=/Users/qa/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0:/Users/qa/.gem/ruby/2.1.0

bash-3.2$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.3
  - RUBY VERSION: 2.1.5 (2014-11-13 patchlevel 273) [x86_64-darwin14.0]
  - INSTALLATION DIRECTORY: /Users/qa/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0
  - USER INSTALLATION DIRECTORY: /Users/qa/.gem/ruby/2.1.0
  - RUBY EXECUTABLE: /Users/qa/.rvm/rubies/ruby-2.1.5/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/qa/.rvm/rubies/ruby-2.1.5/bin
  - SPEC CACHE DIRECTORY: /Users/qa/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-14
  - GEM PATHS:
     - /Users/qa/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0
     - /Users/qa/.gem/ruby/2.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/qa/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/bin
     - /Users/qa/.rvm/gems/ruby-2.1.5/bin
     - /Users/qa/.rvm/gems/ruby-2.1.5@global/bin
     - /Users/qa/.rvm/rubies/ruby-2.1.5/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /local/adt-bundle-mac-x86_64-LATEST/sdk/platform-tools
     - /local/adt-bundle-mac-x86_64-LATEST/sdk/tools
     - /Users/qa/bin
     - /Users/qa/.rvm/bin

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
This actually should now be fixed on master

**Comment by sslgeorge** [comment]
This has not been fixed, I still get the same error, I still get the same error

**Comment by drbrain** [comment]
@sslgeorge you'll probably need to upgrade rubygems manually, follow the instructions for "If you don't have any RubyGems installed" here: https://rubygems.org/pages/download

**Comment by bronzdoc** [comment]
This should be fixed in 2.6.10

**Comment by hansemannn** [comment]
Still hitting this one with 2.7.0 / high-sierra.
