### ISSUE TITLE
unable to download from rubygems

### ISSUE THREAD

**Issue by Steveo00** [rubygems/rubygems#2322]
I am trying to install Rails 5.1.3 and the associated gems. My problem is that I am unable to download any gems from Rubygems site.

Similar issues have been raised previously but the solutions suggested do not seem to work in my case.

The following are error messages that I am receiving:

$ sudo gem update --system
[sudo] password for steve:
ERROR: While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
timed out (https://api.rubygems.org/specs.4.8.gz)

$ gem install rails --version=5.1.3 --no-ri --no-rdoc
ERROR: Could not find a valid gem 'rails' (= 5.1.3), here is why:
Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)

I have successfully installed Ruby 2.4.1 using rbenv

I am able to get to https://rubygems.org directly from the same machine I am attempting the above on. 

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x ] The command line `gem`
  - [ ] Other

Here are my current environment details:
I am using Ubuntu 16.04 on HP laptop.
Gem env version is 2.6.11
Bundler version is 1.16.1
Any assistance or suggestions would be greatly appreciated.

**Comment by bronzdoc** [comment]
```
gem install rails --version=5.1.3 --no-ri --no-rdoc
Fetching: i18n-0.9.5.gem (100%)
Successfully installed i18n-0.9.5
Fetching: activesupport-5.1.3.gem (100%)
Successfully installed activesupport-5.1.3
Fetching: rack-2.0.5.gem (100%)
Successfully installed rack-2.0.5
Fetching: rack-test-0.6.3.gem (100%)
Successfully installed rack-test-0.6.3
Fetching: mini_portile2-2.3.0.gem (100%)
Successfully installed mini_portile2-2.3.0
Fetching: nokogiri-1.8.3.gem (100%)
Building native extensions. This could take a while...
Successfully installed nokogiri-1.8.3
Fetching: crass-1.0.4.gem (100%)
Successfully installed crass-1.0.4
Fetching: loofah-2.2.2.gem (100%)
Successfully installed loofah-2.2.2
Fetching: rails-html-sanitizer-1.0.4.gem (100%)
Successfully installed rails-html-sanitizer-1.0.4
Fetching: rails-dom-testing-2.0.3.gem (100%)
Successfully installed rails-dom-testing-2.0.3
Fetching: builder-3.2.3.gem (100%)
Successfully installed builder-3.2.3
Fetching: erubi-1.7.1.gem (100%)
Successfully installed erubi-1.7.1
Fetching: actionview-5.1.3.gem (100%)
Successfully installed actionview-5.1.3
Fetching: actionpack-5.1.3.gem (100%)
Successfully installed actionpack-5.1.3
Fetching: activemodel-5.1.3.gem (100%)
Successfully installed activemodel-5.1.3
Fetching: arel-8.0.0.gem (100%)
Successfully installed arel-8.0.0
Fetching: activerecord-5.1.3.gem (100%)
Successfully installed activerecord-5.1.3
Fetching: globalid-0.4.1.gem (100%)
Successfully installed globalid-0.4.1
Fetching: activejob-5.1.3.gem (100%)
Successfully installed activejob-5.1.3
Fetching: mini_mime-1.0.0.gem (100%)
Successfully installed mini_mime-1.0.0
Fetching: mail-2.7.0.gem (100%)
Successfully installed mail-2.7.0
Fetching: actionmailer-5.1.3.gem (100%)
Successfully installed actionmailer-5.1.3
Fetching: nio4r-2.3.1.gem (100%)
Building native extensions. This could take a while...
Successfully installed nio4r-2.3.1
Fetching: websocket-extensions-0.1.3.gem (100%)
Successfully installed websocket-extensions-0.1.3
Fetching: websocket-driver-0.6.5.gem (100%)
Building native extensions. This could take a while...
Successfully installed websocket-driver-0.6.5
Fetching: actioncable-5.1.3.gem (100%)
Successfully installed actioncable-5.1.3
Fetching: railties-5.1.3.gem (100%)
Successfully installed railties-5.1.3
Fetching: sprockets-3.7.1.gem (100%)
Successfully installed sprockets-3.7.1
Fetching: sprockets-rails-3.2.1.gem (100%)
Successfully installed sprockets-rails-3.2.1
Fetching: rails-5.1.3.gem (100%)
Successfully installed rails-5.1.3
30 gems installed
```

I can't reproduce your error, is this still a problem for you @Steveo00 ?

**Comment by Steveo00** [comment]
Hi Luis

Unfortunately I still do and its very frustrating because I have not had
this problem before.

The following are details about my system. I am on Ubuntu 16.04.

Details are:

steve@steve-HP-ProBook-650-G3:~/work$ bundler -v
Bundler version 1.16.1
steve@steve-HP-ProBook-650-G3:~/work$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
steve@steve-HP-ProBook-650-G3:~/work$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.11
  - RUBY VERSION: 2.4.1 (2017-03-22 patchlevel 111) [x86_64-linux]
  - INSTALLATION DIRECTORY:
/home/steve/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0
  - USER INSTALLATION DIRECTORY: /home/steve/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: /home/steve/.rbenv/versions/2.4.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/steve/.rbenv/versions/2.4.1/bin
  - SPEC CACHE DIRECTORY: /home/steve/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/steve/.rbenv/versions/2.4.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/steve/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0
     - /home/steve/.gem/ruby/2.4.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/steve/.rbenv/versions/2.4.1/bin
     - /home/steve/.rbenv/libexec
     - /home/steve/.rbenv/plugins/ruby-build/bin
     - /home/steve/.rbenv/shims
     - /home/steve/.rbenv/bin
     - /home/steve/.rbenv/plugins/ruby-build/bin
     - /home/steve/.rbenv/plugins/ruby-build/bin
     - /home/steve/.rbenv/shims
     - /home/steve/.rbenv/bin
     - /home/steve/bin
     - /home/steve/.local/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
steve@steve-HP-ProBook-650-G3:~/work$ gem install rails --version=5.1.3
--no-ri --no-rdoc
ERROR:  Could not find a valid gem 'rails' (= 5.1.3), here is why:
          Unable to download data from https://rubygems.org/ - timed out (
https://api.rubygems.org/specs.4.8.gz)

I had previously successfully installed Rails 5.1.4 so I tried to create a
new app as follows but had the same problem trying to install the required
gems. The following is the system output:

steve@steve-HP-ProBook-650-G3:~/work$ rails -v
Rails 5.1.4
steve@steve-HP-ProBook-650-G3:~/work$ rails new demo
      create
      create  README.md
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /home/steve/work/demo/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/javascripts/application.js
      create  app/assets/javascripts/cable.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/assets/javascripts/channels
      create  app/assets/javascripts/channels/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/update
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/secrets.yml
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_5_1.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  tmp
      create  tmp/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  package.json
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_5_1.rb
         run  bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms
Bundler is installing for. Bundler is installing for ruby but the
dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add
those platforms to the bundle, run `bundle lock --add-platform x86-mingw32
x86-mswin32 x64-mingw32 java`.
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch
specs from https://rubygems.org/

The system tries 4 times before failing.

The 'rails new demo' command creates all the required directories and files.

The following is the contents of the Gemfile that was created:

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more:
https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger
console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %>
anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the
background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

There have been others users with same issue as reported on Rubygems site.
They havent proposed a solution

Any advice or assistance would be greatly appreciated.

Regards,

Steve

**Comment by rozetko** [comment]
Hey @Steveo00! I had the exact problem on my Ubuntu 16.04 in WSL. 

The problem was in IPv6, actually. I just followed [this guide](https://www.reddit.com/r/bashonubuntuonwindows/comments/7u1le5/disable_ipv6_or_prefer_ipv4_first/dtlnmzu/) to make IPv4 be used first and problem disappeared.

**Comment by willrodriguez** [comment]
We were able to solve our issues using
```shell
sudo apt-get install ca-certificates curl libcurl3 libcurl3-gnutls openssl libssl-dev libssl-doc libssl1.0.0
```

**Comment by bronzdoc** [comment]
@Steveo00  could you try what @rozetko and @willrodriguez suggest? i still can't reproduce the issue.

**Comment by Steveo00** [comment]
Hi

I tried both suggested solutions. @rozetko resolved my issue but
@willrodriguez didn't.

Please let me know if you need further info.

Thanks so much for everyones help. I would not have resolved this myself.

Regards,

Steve

**Comment by bronzdoc** [comment]
Great to hear the problem is solved @Steveo00 ! i'g going to close this issue now.

**Comment by 42Bastian** [comment]
Issue still exists: On win10 I had to disable IPv6 to run "gem".

**Comment by deivid-rodriguez** [comment]
Would you be able to apply #2662 and see if that fixes things for you? There's instructions in that thread to get the PR applied to your rubygems install.

**Comment by 42Bastian** [comment]
> 
> 
> Would you be able to apply #2662 and see if that fixes things for you? There's instructions in that thread to get the PR applied to your rubygems install.

Works on win10!

**Comment by deivid-rodriguez** [comment]
That's great to hear @42Bastian, thanks for trying it!

**Comment by arielsashcov** [comment]
For me it was the DNS server. 

> The DNS server seems out of order. You can use another DNS server such as 8.8.8.8. Put nameserver 8.8.8.8 to the first line of /etc/resolv.conf

https://stackoverflow.com/questions/24821521/wget-unable-to-resolve-host-address-http
