### ISSUE TITLE
Two circular require warnings from test suite

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2548]
Using `ruby 2.6.0dev (2018-12-24 trunk 66515) [x64-mingw32]`

and
```
rake test RUBYOPT=--verbose TEST=test/rubygems/test_gem.rb TESTOPTS=-v
```

`warning: loading in progress, circular require considered harmful` occurs during:

```
TestGem#test_looks_for_gemdeps_files_automatically_on_start
TestGem#test_looks_for_gemdeps_files_automatically_on_start_in_parent_dir
```

I'd check on Travis with Ubuntu & MacOS, but I can't because of Issue #2451...

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
trunk & master
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Just tested this in Ubuntu(Ubuntu 18.04.1 LTS) and MacOS(Mojave) and the warning is happening in both systems...

**Comment by MSP-Greg** [comment]
I still see this everyday with the trunk build on ruby-loco.  For Travis see:
https://travis-ci.org/ruby/ruby/jobs/523081688#L2679

Is this a Bundler issue?

**Comment by deivid-rodriguez** [comment]
I think this should get fixed by https://github.com/bundler/bundler/pull/7062.

**Comment by bronzdoc** [comment]
Just for the record, i just tested this with bundler/bundler#7062 and the problem still persists.

**Comment by deivid-rodriguez** [comment]
If it persists, it must persist in some other way because in the warnings mentioned, the `overwrite_loaded_gem_version` method appears in the backtrace, and that all has been removed in  bundler/bundler#7062.

**Comment by bronzdoc** [comment]
This should be fixed now @MSP-Greg

**Comment by MSP-Greg** [comment]
@bronzdoc 

All good. Thank you.
