### ISSUE TITLE
`gem yank` + 2FA requires OTP, but has no way to provide it

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems#2790]
My current problem is that, if you have 2FA enabled, `gem yank` requires a OTP -- but doesn't prompt you for one, and doesn't accept a `--otp <...>` flag.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by indirect** [comment]
Any interest in sending a PR to fix it? 🙂

**Comment by duckinator** [comment]
I'll give it a shot next week. :+1:

**Comment by duckinator** [comment]
Apparently:

1. I forgot to follow-up on this.
2. #2514 added this in _February_, but it hasn't been included in a release yet.

So I'm going to close this issue, since the next release should resolve it.

**Comment by andyjeffries** [comment]
I'm still seeing this now in November. How can I get around this? I can't push the second (functional) release of my gem because I changed the case of the gem, and now I can't yank the old (unusable) one either.

**Comment by andyjeffries** [comment]
Never mind, I got round it by disabling 2FA, yanking and then re-enabling. Not ideal, but a workaround... https://rubygems.org/profile/edit

**Comment by duckinator** [comment]
It looks like RubyGems v3.0.6 includes commits that are as recent as August of this year, but not the commits from #2514.

However, though the changes are in [`lib/rubygems/commands/yank_command.rb` on master](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/commands/yank_command.rb).

I'm not sure what's up, so I'm gonna reopen this for now.

@indirect @bronzdoc do either of you know what's up with this? (Or, alternatively, who I should ask about it?)

**Comment by deivid-rodriguez** [comment]
It sounds like it was not backported to v3.0.6. We should either milestone it for 3.0.7, or wait until we release 3.1.0. Also, `gem update --system --pre` should probably include it.

**Comment by duckinator** [comment]
@deivid-rodriguez thanks for the info. :+1:

**Comment by duckinator** [comment]
I confirmed that `gem update --system --pre` includes it.

@andyjeffries with the release of 3.1.0 I think this should be properly resolved.

**Comment by andyjeffries** [comment]
Thanks @duckinator !

**Comment by duckinator** [comment]
Closing since this is fixed in the latest version.

**Comment by jasonfb** [comment]
as of this writing, gem version is now 3.1.4 so you no longer need to use `--pre` (which I think will get the prerelease)

I think a lot of people forget that rubygems doesn't normally update itself so it's easy to stay on an older version of rubygems

to update past 3.0.9, use
```
gem update --system
```

I am cross-posting to stack overflow here
https://stackoverflow.com/questions/68183450/gem-yank-3-1-0-returns-you-have-enabled-multifactor-authentication-but-no-ot/68183492#68183492
