### ISSUE TITLE
CI Use - stop multi-line output of gem update --system

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2907]
Some CI providers collapse output in their logs, others do not.  Some update RG & Bundler for older Ruby releases, some do not.

While running `gem update --system` in CI, it outputs over 1,000 lines of very helpful version history.

I tried `--no-post-install-message` which didn't do anything.  I tried `--silent`, which threw a `invalid option: --silent` error and stopped the update, even though it appears in `gem update --help` as a common option.

When one is wrestling with intermittent tests, differing results by CI provider and OS, everything sets one off.

Please tell me there is some way to stop the output?

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
@MSP-Greg what version of rubygems is CI using?

**Comment by MSP-Greg** [comment]
It varies.  I believe both Travis & AppVeyor update RubyGems & Bundler in their Ruby builds.

GitHub Actions does not.  An example at https://github.com/puma/puma/pull/1918/checks?check_run_id=218917392.  Every 'RubyGems, Bundler Update' step has some output.

I apologize, as the output varies depending on the version one upgrades from.

Regardless, it would be nice to be able to silence it...

**Comment by MSP-Greg** [comment]
Maybe silence the output if `ENV['CI']` exists?

**Comment by bronzdoc** [comment]
@MSP-Greg  does `gem update --system --silent` doesn't silence output with the last Rubygems version for you?

**Comment by MSP-Greg** [comment]
@bronzdoc

Here's a GtiHub Actions build: https://github.com/MSP-Greg/puma/runs/219228112 with `--silent` added.

**Comment by Beerzaa304** [comment]
> Will give it a look @MSP-Greg thanks

**Comment by duckinator** [comment]
I did some poking around about this.

`gem update --system` basically installs the rubygems-update gem, `cd`s to the directory containing that gem, and runs `ruby --disable-gems setup.rb <args>` where `<args>` are determined by `Gem::Commands::UpdateCommand#update_rubygems_arguments`.

However, if you look at that function, it does not preserve `--silent`: https://github.com/rubygems/rubygems/blob/master/lib/rubygems/commands/update_command.rb#L256-L265

But it looks like setup.rb, when run manually, does support it.

So I think, basically, that function may just need something along the lines of `args << '--silent' if options[:silent]`?

---

**WORKAROUND:** `gem install --silent rubygems-update && cd $RUBYGEMS_UPDATE_DIR && ruby --disable-gems setup.rb --silent`

Where `$RUBYGEMS_UPDATE_DIR` is wherever it got installed to. On my system, that's `/usr/share/gems/gems/rubygems-update-3.0.6`.

**Comment by cussiol** [comment]
`--silent` flag still does not work for rubygems 3.1.3. Just like `--quiet` and `--no-post-install-message` aren't working either.

**Comment by deivid-rodriguez** [comment]
> So I think, basically, that function may just need something along the lines of args << '--silent' if options[:silent]?

Sorry I never replied to this, but from what I remember from this part of the code, this seems like it would work. I tend to recall using the same thing for the `--force` flag, but not fully sure. Would you like to put together a PR?

**Comment by duckinator** [comment]
@deivid-rodriguez I made an attempt at it over in #3789, but am not sure how to test it.

**Comment by duckinator** [comment]
This should be fixed whenever a release is made that includes the changes from PR #3789.

**Comment by deivid-rodriguez** [comment]
We normally close tickets as fixes land into master, so I guess we can close this as fixed by #3789?

**Comment by duckinator** [comment]
@deivid-rodriguez yeah, I'll go ahead and close it. Not sure why I didn't before lol

**Comment by grosser** [comment]
plz reopen, still happening `gem update --silent --system 3.2.4`

**Comment by deivid-rodriguez** [comment]
Yeah, I think the setup command is still not respecting `--silent`.

**Comment by duckinator** [comment]
My understanding is you have to be upgrading _from_ a version with the fix from #3789 in order for it to work.

It looks like the fix landed in 3.2.0, so if the version you're updating from is older than 3.2.0, it won't work.

@grosser do you know what RubyGems version you were updating from?

**Comment by grosser** [comment]
Did this and works as expected ... can close I guess since this will then solve itself in a few months time :)
```
  gem update --silent --system 3.2.1 && \
  echo DONE && \
  gem update --silent --system 3.2.4 && \
```

**Comment by duckinator** [comment]
Sounds good! :+1:

**Comment by deivid-rodriguez** [comment]
Nice, thanks for the clarification @duckinator!
