### ISSUE TITLE
fish shell not setting the correct exit status flag in bundle check

### ISSUE THREAD

**Issue by danielpclark** [rubygems/rubygems#3233]
According to the website: https://bundler.io/man/bundle-check.1.html

> check searches the local machine for each of the gems requested in the Gemfile. If all gems are found, Bundler prints a success message and exits with a status of 0.
>
> If not, the first missing gem is listed and Bundler exits status 1.

When I change a gem version in the `Gemfile` without running `bundle install` or `bundle update` I get the following message from `bundle check`:

    Bundler can't satisfy your Gemfile's dependencies.
    Install missing gems with `bundle install`.

And the exit status is always `0`.

This is not the desired behavior.  I need the exit status to be a non-zero number at least.

## Environment

```
Bundler             1.17.1
  Platforms         ruby, x86_64-linux
Ruby                2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
  Full Path         /home/user/.rvm/rubies/ruby-2.5.3/bin/ruby
  Config Dir        /home/user/.rvm/rubies/ruby-2.5.3/etc
RubyGems            2.7.7
  Gem Home          /home/user/.rvm/gems/ruby-2.5.3
  Gem Path          /home/user/.rvm/gems/ruby-2.5.3:/home/user/.rvm/gems/ruby-2.5.3@global
  User Path         /home/user/.gem/ruby/2.5.0
  Bin Dir           /home/user/.rvm/gems/ruby-2.5.3/bin
Tools               
  Git               2.17.1
  RVM               1.29.4 latest
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2018-10-25
Git SHA           2760d72d3
Released Version  true
```

## Bundler settings

```
gem.test
  Set for the current user (/home/user/.bundle/config): "minitest"
gem.mit
  Set for the current user (/home/user/.bundle/config): true
gem.coc
  Set for the current user (/home/user/.bundle/config): false
```

**Comment by deivid-rodriguez** [comment]
Hi @danielpclark. I just tried this a got the proper result, so maybe this is something with your environment or has been fixed in recent versions. I honestly can't imagine how this could be a problem in bundler though.

**Comment by danielpclark** [comment]
I'm still experiencing this.  To reproduce I put a gem in the Gemfile, did not install it, and then the commands above.

## Environment                                                                                                                                                            [969/1312]
                                                                                                                                                                                    
```                                          
Bundler       2.1.4                                                                       
  Platforms   ruby, x86_64-linux                                                          
Ruby          2.7.1p83 (2020-03-31 revision a0c7c23c9cec0d0ffcba012279cd652d28ad5bf3) [x86_64-linux]
  Full Path   /home/danielpclark/.rbenv/versions/2.7.1/bin/ruby
  Config Dir  /home/danielpclark/.rbenv/versions/2.7.1/etc
RubyGems      3.1.4            
  Gem Home    /home/danielpclark/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0                
  Gem Path    /home/danielpclark/.gem/ruby/2.7.0:/home/danielpclark/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0
  User Home   /home/danielpclark             
  User Path   /home/danielpclark/.gem/ruby/2.7.0                                          
  Bin Dir     /home/danielpclark/.rbenv/versions/2.7.1/bin
Tools                                                                                     
  Git         2.25.1                                                                      
  RVM         not installed                                                               
  rbenv       rbenv 1.1.2-11-gc46a970     
  chruby      not installed                                                                                                                                                         
```                                                                                                                                                                                 
                                                                                                                                                                                    
## Bundler Build Metadata          
                                             
```                                          
Built At          2020-06-03                                                                                                                                                        
Git SHA           32a4159325                                                              
Released Version  false
```

**Comment by deivid-rodriguez** [comment]
I think this might be either an issue in your environment or a bug in fish. I recommend that you have a look at existing issues in the fish repo, and that you try to minimize your shell configuration if you have any.

I also tried to repro this under docker to make sure it was not something specific on my environment making this work.

Running `docker build . -t foo && docker run foo` with the following `Dockerfile` prints "1" as expected.

```Dockerfile

FROM ruby:2.7

RUN apt update && apt install fish -y

RUN echo 'gem "activesupport"' > Gemfile

CMD fish -c 'bundle check; echo $status'
```

Maybe you can try reporting this to the fish project. I image you could have some hooks that run some stuff after every command, for example to set the prompt or something, that could be interfering here.

**Comment by danielpclark** [comment]
It seems I had a wrapper function written for fish in `~/.config/fish/functions/bundle.fish` so it's my fault for not handling the return value on this.  Thanks!

**Comment by deivid-rodriguez** [comment]
No problem, glad we figured it out! :)
