### ISSUE TITLE
CGI escape error. Bundle config does not work with username as email.

### ISSUE THREAD

**Issue by domi-nika60** [rubygems/rubygems#3250]
Hi,

recently I have noticed, that the the command
`bundle config HOST_NAME username:password` is not working for username as email.
The library does not accept @ symbol. This situation does not provoke any error or program exit, but when I've been using next `bundle install`  the error is:
**`Please CGI escape your usernames and passwords before setting them for authentication.`**

**Comment by deivid-rodriguez** [comment]
I believe (from the linked issue) that this was due to some problem that was fixed in newer rubygems versions. If you can provide a repro using the latest rubygems version, please reopen!

**Comment by saschpe** [comment]
It remains an issue with Ruby-2.7. We can't move to Ruby-3.x because of CocoaPods for iOS projects.

**Comment by sephethus** [comment]
What if I don't have username as email and it still throws this stupid error? I am using just the username:token format. No at symbol.

**Comment by hashtjekvik** [comment]
any update on this issue please, I got stuck too with ruby 2.7.2

**Comment by deivid-rodriguez** [comment]
Does it work if you upgrade rubygems with `gem update --system`?

**Comment by silverhammermba** [comment]
I just ran into this issue on Windows, my problem was that I was quoting the credentials (thinking this was needed for my shell to interpret them correctly), but in fact it was passing the quotation marks on to the gem install. So it was telling me to CGI escape because it saw the `"` character.

So if anyone is running into this I recommend double checking how you are injecting the credentials and to ensure you don't end up with extra characters in there such as quotes or spaces.

It would be helpful if the error printed the offending character that needs to be escaped rather than making you guess what it was.
