### ISSUE TITLE
Bundler not working as expected for cross-platform gems

### ISSUE THREAD

**Issue by xam7247** [rubygems/rubygems#3371]
After going through rubygems/bundler#5863, rubygems/bundler#4517, rubygems/bundler#646, rubygems/bundler#2040, rubygems/bundler#2283, bundler/bundler-features#4, and many more issues on the same note, I still face this issue.

**Development machine:** Windows
**CI machine:** Linux (No internet connection, no other Linux machine available to generate a *nix based Gemfile / caching the gems)
**Ruby:** v2.3.3
**Bundler:** v1.15.1

**Gemfile:**
```
source 'https://rubygems.org'

gem 'rspec', '>= 3.4.0'
gem 'colorize'
gem 'mongo'
gem 'json'
gem 'capybara'
gem "json-schema"
gem 'rubyXL'
gem "roo", "~> 2.7.0"
gem "rest-client", "2.0.2"
gem "ffi"
gem "unf_ext"
gem "nokogiri"
```

**Gemfile.lock**
```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    bson (4.2.2)
    capybara (2.15.1)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    colorize (0.8.1)
    diff-lcs (1.3)
    domain_name (0.5.20170404)
      unf (>= 0.0.5, < 1.0.0)
    ffi (1.9.18)
    ffi (1.9.18-x64-mingw32)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    json (2.1.0)
    json-schema (2.8.0)
      addressable (>= 2.4)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_mime (0.1.4)
    mini_portile2 (2.2.0)
    mongo (2.4.3)
      bson (>= 4.2.1, < 5.0.0)
    netrc (0.11.0)
    nokogiri (1.8.0)
      mini_portile2 (~> 2.2.0)
    nokogiri (1.8.0-x64-mingw32)
      mini_portile2 (~> 2.2.0)
    public_suffix (3.0.0)
    rack (2.0.3)
    rack-test (0.7.0)
      rack (>= 1.0, < 3)
    rest-client (2.0.2)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    rest-client (2.0.2-x64-mingw32)
      ffi (~> 1.9)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    roo (2.7.1)
      nokogiri (~> 1)
      rubyzip (~> 1.1, < 2.0.0)
    rspec (3.6.0)
      rspec-core (~> 3.6.0)
      rspec-expectations (~> 3.6.0)
      rspec-mocks (~> 3.6.0)
    rspec-core (3.6.0)
      rspec-support (~> 3.6.0)
    rspec-expectations (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-mocks (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-support (3.6.0)
    rubyXL (3.3.26)
      nokogiri (>= 1.4.4)
      rubyzip (>= 1.1.6)
    rubyzip (1.2.1)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.4)
    unf_ext (0.0.7.4-x64-mingw32)
    xpath (2.1.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby
  x64-mingw32

DEPENDENCIES
  capybara
  colorize
  ffi
  json
  json-schema
  mongo
  nokogiri
  rest-client (= 2.0.2)
  roo (~> 2.7.0)
  rspec (>= 3.4.0)
  rubyXL
  unf_ext

BUNDLED WITH
   1.15.1

```
As per https://github.com/bundler/bundler/issues/5863, I did:
`bundle config specific_platform true`
`bundle lock --add-platform ruby`
`bundle package --all-platforms`

Doing this, Bundler did download the gems for other platform ('ruby' in this case), along with gem files for current platform ('x64-mingw32').

**Note:** I had to add the dependent gems 'ffi', 'unf_ext' and 'nokogiri' since bundler was not downloading other platform gems unless these were explicitly mentioned in Gemfile.

**Problem:**
After this, when you do `bundle install --local` (on the windows machine), it installs gems from vendor/cache, but throws an error randomly for one of the cross-platform gems.
e.g., "`Some gems seem to be missing from your vendor/cache directory. Could not find ffi-1.9.18 in any of the sources`"

Post this, `bundle exec ...` still works.

So: 
- The error is misleading since the gem file is in fact available in vendor/cache. 
- And we need to to explain to each team mate to ignore the error due to a known caveat in Bundler.
- And we need to be super careful when adding new gems, to ensure the "missing gems" is not a false alarm.

Any solutions would be much appreciated.

**Comment by deivid-rodriguez** [comment]
Could you try https://github.com/rubygems/rubygems/pull/4022 and verify whether it fixes this issue? Thanks!

**Comment by deivid-rodriguez** [comment]
I'll assume issue is fixed by mentioned PR.

**Comment by xam7247** [comment]
> Could you try #4022 and verify whether it fixes this issue? Thanks!

@deivid-rodriguez : Unfortunately I don't have access to a windows machine anymore. So until someone else lands into the same issue, we can rightly assume that #4022 might have fixed this 👍

**Comment by steakknife** [comment]
Not fixed and not working in bundler 2.4.2 on Windows, Mac, and Linux. Either `bundle cache --all-platforms --no-install` grabs only ruby platform gems or the current native platform. There are use-cases where vendor/cache needs to be shipped to work offline and standalone.

**Comment by deivid-rodriguez** [comment]
Please report a separate issue with repro steps. Thank you.

**Comment by steakknife** [comment]
:+1: I'll scare up a MCE Dockerfile when I have a chance.

**Comment by steakknife** [comment]
Is multiplatform FOSS testing and on-demnd testing still a PITA?

At work, we have to run Ruby-based software in extremely
heterogeneous use-cases.
