### ISSUE TITLE
`rake release` not working with Bundler 2.2.3

### ISSUE THREAD

**Issue by schneems** [rubygems/rubygems#4218]
### Post steps to reproduce the problem

Trying to release a gem fails with Bundler 2.2.3 with Ruby 3.0.0

```
$ bundle exec rake release
dead_end 1.1.1 built to pkg/dead_end-1.1.1.gem.
Tagged v1.1.1.
Untagging v1.1.1 due to error.
rake aborted!
Running `git config --get branch.heads/v1.1.1.remote` failed. Run this command directly for more detailed output.
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/gem_helper.rb:204:in `sh'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/gem_helper.rb:128:in `default_remote'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/gem_helper.rb:118:in `git_push'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/gem_helper.rb:71:in `block (2 levels) in install'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/gem_helper.rb:174:in `tag_version'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/gem_helper.rb:71:in `block in install'
/Users/rschneeman/.gem/ruby/3.0.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
/Users/rschneeman/.gem/ruby/3.0.0/bin/bundle:23:in `load'
/Users/rschneeman/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
Tasks: TOP => release => release:source_control_push
(See full trace by running task with --trace)
```

Debugging

```
$ git config --get branch.heads/v1.1.1.remote
$ echo $?
1
$ bundle -v
Bundler version 2.2.3
```

Works with Bundler 2.1.4 just fine:

```
$ gem install bundler -v 2.1.4
Fetching bundler-2.1.4.gem
Successfully installed bundler-2.1.4
Parsing documentation for bundler-2.1.4
Installing ri documentation for bundler-2.1.4
Done installing documentation for bundler after 3 seconds
1 gem installed
$ bundle _2.1.4_ exec rake release
dead_end 1.1.1 built to pkg/dead_end-1.1.1.gem.
Tagged v1.1.1.
Pushed git commits and tags.
Pushing gem to https://rubygems.org...
You have enabled multi-factor authentication. Please enter OTP code.
Code:   *********
Successfully registered gem: dead_end (1.1.1)
Pushed dead_end 1.1.1 to rubygems.org
```

### Which command did you run?

```
bundle exec rake release
```

### What were you expecting to happen?

To release the gem 

### What actually happened?

Error instructing me to run a command for debugging. When I run the command for debugging, no output shows.

### If not included with the output of your command, run `bundle env` and paste the output below

<details><summary>bundle env</summary>

## Environment

```
Bundler       2.2.3
  Platforms   ruby, x86_64-darwin-19
Ruby          3.0.0p0 (2020-12-25 revision 95aff214687a5e12c3eb57d056665741e734c188) [x86_64-darwin19]
  Full Path   /Users/rschneeman/.rubies/ruby-3.0.0/bin/ruby
  Config Dir  /Users/rschneeman/.rubies/ruby-3.0.0/etc
RubyGems      3.2.3
  Gem Home    /Users/rschneeman/.gem/ruby/3.0.0
  Gem Path    /Users/rschneeman/.gem/ruby/3.0.0:/Users/rschneeman/.rubies/ruby-3.0.0/lib/ruby/gems/3.0.0
  User Home   /Users/rschneeman
  User Path   /Users/rschneeman/.gem/ruby/3.0.0
  Bin Dir     /Users/rschneeman/.gem/ruby/3.0.0/bin
Tools
  Git         2.28.0
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2020-12-22
Git SHA           29dc3c8398
Released Version  true
```

## Bundler settings

```
jobs
  Set for the current user (/Users/rschneeman/.bundle/config): 8
build.nokogiri
  Set for the current user (/Users/rschneeman/.bundle/config): "--use-system-libraries"
gem.test
  Set for the current user (/Users/rschneeman/.bundle/config): "rspec"
gem.mit
  Set for the current user (/Users/rschneeman/.bundle/config): true
gem.coc
  Set for the current user (/Users/rschneeman/.bundle/config): true
--path
  Set for the current user (/Users/rschneeman/.bundle/config): "vendor/"
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in dead_end.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem "stackprof"
```

### Gemfile.lock

```
PATH
  remote: .
  specs:
    dead_end (1.1.1)

GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.4.4)
    rake (12.3.3)
    rspec (3.10.0)
      rspec-core (~> 3.10.0)
      rspec-expectations (~> 3.10.0)
      rspec-mocks (~> 3.10.0)
    rspec-core (3.10.0)
      rspec-support (~> 3.10.0)
    rspec-expectations (3.10.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-mocks (3.10.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-support (3.10.0)
    stackprof (0.2.16)

PLATFORMS
  ruby

DEPENDENCIES
  dead_end!
  rake (~> 12.0)
  rspec (~> 3.0)
  stackprof

BUNDLED WITH
   2.2.3
```

### dead_end.gemspec

```ruby
# frozen_string_literal: true

require_relative 'lib/dead_end/version'

Gem::Specification.new do |spec|
  spec.name          = "dead_end"
  spec.version       = DeadEnd::VERSION
  spec.authors       = ["schneems"]
  spec.email         = ["richard.schneeman+foo@gmail.com"]

  spec.summary       = %q{Find syntax errors in your source in a snap}
  spec.description   = %q{When you get an "unexpected end" in your syntax this gem helps you find it}
  spec.homepage      = "https://github.com/zombocom/dead_end.git"
  spec.license       = "MIT"
  spec.required_ruby_version = Gem::Requirement.new(">= 2.5.0")

  spec.metadata["homepage_uri"] = spec.homepage
  spec.metadata["source_code_uri"] = "https://github.com/zombocom/dead_end.git"

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  spec.files         = Dir.chdir(File.expand_path('..', __FILE__)) do
    `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  end
  spec.bindir        = "exe"
  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]
end
```
</details>

**Comment by deivid-rodriguez** [comment]
Thanks @schneems for this ticket.

This is my bad, I thought `git branch --get branch.<name>.remote` returned an successful empty status if the branch doesn't have a remote. But it turns out it returns a failure status. Not sure how I missed this since the latter sounds more reasonable...

Anyways, sorry, let me fix it.

**Comment by deivid-rodriguez** [comment]
It turned out to be much trickier than I expected but I believe https://github.com/rubygems/rubygems/pull/4219 should fix this.

@schneems Can you confirm that you release from a git branch with the same name as the git tag being pushed?

**Comment by schneems** [comment]
Sorry for the radio silence here. I'm still seeing the error with bundler 2.2.6:

```
$ bundle --version
Bundler version 2.2.6
$ bundle exec rake release
dead_end 1.1.3 built to pkg/dead_end-1.1.3.gem.
Tagged v1.1.3.
Untagging v1.1.3 due to error.
rake aborted!
Running `git config --get branch.module_function.remote` failed. Run this command directly for more detailed output.
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/gem_helper.rb:204:in `sh'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/gem_helper.rb:128:in `default_remote'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/gem_helper.rb:118:in `git_push'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/gem_helper.rb:71:in `block (2 levels) in install'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/gem_helper.rb:174:in `tag_version'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/gem_helper.rb:71:in `block in install'
/Users/rschneeman/.gem/ruby/3.0.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/cli/exec.rb:63:in `load'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/cli/exec.rb:28:in `run'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/cli.rb:494:in `exec'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/cli.rb:30:in `dispatch'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/cli.rb:24:in `start'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/exe/bundle:49:in `block in <top (required)>'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/exe/bundle:37:in `<top (required)>'
/Users/rschneeman/.gem/ruby/3.0.0/bin/bundle:23:in `load'
/Users/rschneeman/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
Tasks: TOP => release => release:source_control_push
(See full trace by running task with --trace)
$ git config --get branch.module_function.remote
$ echo $?
1
```

Can we re-open or you want me to make another issue? It's slightly different as it's not the same branch name as the version number.
