### ISSUE TITLE
Adding platform without version does not add current-platform version of libv8 to specs on macOS

### ISSUE THREAD

**Issue by owst** [rubygems/rubygems#4370]
We're in the process of upgrading from Bundler 1.17.2 to 2.2.9, and as part of that process, I'm attempting to use the improved platform support, but have hit a problem with macOS in that the current-platform specific gem doesn't appear to be added when adding a version-less platform to the lock file. 

Starting with the following Gemfile/Gemfile.lock on my mac, with:
```
$ gem env platform
ruby:x86_64-darwin-18
```

```ruby
source 'https://rubygems.org'

gem 'therubyracer'
```

```
GEM
  remote: https://rubygems.org/
  specs:
    libv8 (3.16.14.19)
    ref (2.0.0)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref

PLATFORMS
  ruby

DEPENDENCIES
  therubyracer

BUNDLED WITH
   1.17.2
```

I first updated to use Bundler 2 (2.2.9) with `gem install bundler` and then `bundle update --bundler` - the only change was to `BUNDLED WITH` which became 2.2.9 as expected. Then I tried to add a versionless mac platform to the lockfile with `bundle lock --add-platform x86_64-darwin`, which succeeded, but the diff doesn't look quite right:
```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index d3e1ab0..2e6acdc 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -2,6 +2,9 @@ GEM
   remote: https://rubygems.org/
   specs:
     libv8 (3.16.14.19)
+    libv8 (3.16.14.19-x86_64-darwin-15)
+    libv8 (3.16.14.19-x86_64-darwin-16)
+    libv8 (3.16.14.19-x86_64-darwin-17)
     ref (2.0.0)
     therubyracer (0.12.3)
       libv8 (~> 3.16.14.15)
@@ -9,6 +12,7 @@ GEM
 
 PLATFORMS
   ruby
+  x86_64-darwin
 
 DEPENDENCIES
   therubyracer
```

specifically, there is no `libv8 (3.16.14.19-x86_64-darwin-18)` (my current platform version). Therefore, a subsequent `bundle install` falls back to `Installing libv8 3.16.14.19 with native extensions`, which I noticed because compiling v8 fails, due to an unrelated problem.

If I manually insert the missing version into the lock file, it _is_ installed without issue. 

Interestingly when I add `x86_64-darwin` to the same `2.2.9` lock file inside a Linux container, the missing line _is_ added:
```
$ docker run --rm -it ruby:2.7.2-slim bash
root@0ad90422559c:/# gem env platform
ruby:x86_64-linux
root@0ad90422559c:/# gem install bundler
Fetching bundler-2.2.9.gem
Successfully installed bundler-2.2.9
1 gem installed
root@0ad90422559c:/# cat > Gemfile
source 'https://rubygems.org'

gem 'therubyracer'
root@0ad90422559c:/# cat > Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    libv8 (3.16.14.19)
    ref (2.0.0)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref

PLATFORMS
  ruby

DEPENDENCIES
  therubyracer

BUNDLED WITH
   2.2.9
root@0ad90422559c:/# bundle lock --add-platform x86_64-darwin
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Writing lockfile to /Gemfile.lock
root@0ad90422559c:/# grep libv8 Gemfile.lock
    libv8 (3.16.14.19)
    libv8 (3.16.14.19-x86_64-darwin-15)
    libv8 (3.16.14.19-x86_64-darwin-16)
    libv8 (3.16.14.19-x86_64-darwin-17)
    libv8 (3.16.14.19-x86_64-darwin-18)
      libv8 (~> 3.16.14.15)
```

We're actually looking to move away from `therubyracer` and thus the ancient version of `libv8` that it depends on and so likely this won't cause a problem for us, but I thought this issue was interesting as it suggests a bug somewhere.

### Which command did you run?

`bundle lock --add-platform x86_64-darwin` is a problem when the current platform is `ruby:x86_64-darwin-18` but not when it is `ruby:x86_64-linux`.

### What were you expecting to happen?

The lock file to include the current platform version  `libv8 (3.16.14.19-x86_64-darwin-18)`.

### What actually happened?

The current platform version was not added to the lock file.

**Comment by deivid-rodriguez** [comment]
Thanks for reporting this @owst. It seems like a bug, indeed, I'll have a look.

**Comment by deivid-rodriguez** [comment]
I wonder whether this is a regression, and whether this might've possibly been fixed by https://github.com/rubygems/rubygems/pull/4371.

**Comment by owst** [comment]
Unfortunately, it doesn't look like #4371 has fixed this issue @deivid-rodriguez - `libv8 (3.16.14.19-x86_64-darwin-18)` is still not added to the lock file

**Comment by deivid-rodriguez** [comment]
Ok, thanks @owst. I figured that would be the case but I thought it was worth confirming it.

**Comment by deivid-rodriguez** [comment]
Can you check whether this works against any versions between 2.2.3 and 2.2.8 (2.2.3 is the one that started locking all matching platform specific variants)? Just to confirm whether this is a regression or a bug present in the original implementation.

**Comment by deivid-rodriguez** [comment]
I can't immediately see what the problem is and I can't repro for mysel since I don't have a machine with `x86_64-darwin-18`. This seems specific to that darwin version somehow, since I tried this [on github actions CI](https://github.com/rubygems/rubygems/runs/1902909954?check_suite_focus=true) (which uses `x86_64-darwin-19`), and all 4 matching variants got added to the lockfile (from `x86_64-darwin-15` to `x86_64-darwin-19`, since there's no `x86_64-darwin-19` specific variant).

**Comment by owst** [comment]
@deivid-rodriguez I've tried all versions from 2.2.2-2.2.11:
- 2.2.2 and 2.2.10 both only add `3.16.14.19-x86_64-darwin-18` to the lock file (not sure if this was expected for 2.2.10?)
- all other versions have the originally-reported behaviour: `3.16.14.19-x86_64-darwin-18` is _not_ added to the lock file but versions for earlier platform versions are

My bash test script (no effort here, please don't judge 😄 ):
```bash
cat > Gemfile <<EOF
source 'https://rubygems.org'

gem 'therubyracer'
EOF

for bundler_patch_version in $(seq 2 11)
do
    bundler_version="2.2.$bundler_patch_version"
    echo -e ">>> Testing bundler v$bundler_version"
    gem install bundler -v "$bundler_version" &> /dev/null

    cat > Gemfile.lock <<EOF
GEM
  remote: https://rubygems.org/
  specs:
    libv8 (3.16.14.19)
    ref (2.0.0)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref

PLATFORMS
  ruby

DEPENDENCIES
  therubyracer

BUNDLED WITH
   $bundler_version
EOF

    bundle version

    bundle lock --add-platform x86_64-darwin

    grep --color libv8 Gemfile.lock
done
```
gives output of
```
$ bash test.sh
>>> Testing bundler v2.2.2
Bundler version 2.2.2 (2020-12-17 commit d85cd5b7c3)
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Writing lockfile to /private/tmp/bundler_issue/Gemfile.lock
    libv8 (3.16.14.19)
    libv8 (3.16.14.19-x86_64-darwin-18)
      libv8 (~> 3.16.14.15)
>>> Testing bundler v2.2.3
Bundler version 2.2.3 (2020-12-22 commit 29dc3c8398)
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Writing lockfile to /private/tmp/bundler_issue/Gemfile.lock
    libv8 (3.16.14.19)
    libv8 (3.16.14.19-x86_64-darwin-15)
    libv8 (3.16.14.19-x86_64-darwin-16)
    libv8 (3.16.14.19-x86_64-darwin-17)
      libv8 (~> 3.16.14.15)
>>> Testing bundler v2.2.4
Bundler version 2.2.4 (2020-12-31 commit 529e536f28)
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Writing lockfile to /private/tmp/bundler_issue/Gemfile.lock
    libv8 (3.16.14.19)
    libv8 (3.16.14.19-x86_64-darwin-15)
    libv8 (3.16.14.19-x86_64-darwin-16)
    libv8 (3.16.14.19-x86_64-darwin-17)
      libv8 (~> 3.16.14.15)
>>> Testing bundler v2.2.5
Bundler version 2.2.5 (2021-01-11 commit ba867aed7f)
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Writing lockfile to /private/tmp/bundler_issue/Gemfile.lock
    libv8 (3.16.14.19)
    libv8 (3.16.14.19-x86_64-darwin-15)
    libv8 (3.16.14.19-x86_64-darwin-16)
    libv8 (3.16.14.19-x86_64-darwin-17)
      libv8 (~> 3.16.14.15)
>>> Testing bundler v2.2.6
Bundler version 2.2.6 (2021-01-19 commit e95bea3837)
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Writing lockfile to /private/tmp/bundler_issue/Gemfile.lock
    libv8 (3.16.14.19)
    libv8 (3.16.14.19-x86_64-darwin-15)
    libv8 (3.16.14.19-x86_64-darwin-16)
    libv8 (3.16.14.19-x86_64-darwin-17)
      libv8 (~> 3.16.14.15)
>>> Testing bundler v2.2.7
Bundler version 2.2.7 (2021-01-27 commit 7bc7ecb660)
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Writing lockfile to /private/tmp/bundler_issue/Gemfile.lock
    libv8 (3.16.14.19)
    libv8 (3.16.14.19-x86_64-darwin-15)
    libv8 (3.16.14.19-x86_64-darwin-16)
    libv8 (3.16.14.19-x86_64-darwin-17)
      libv8 (~> 3.16.14.15)
>>> Testing bundler v2.2.8
Bundler version 2.2.8 (2021-02-02 commit 4015e550dc)
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Writing lockfile to /private/tmp/bundler_issue/Gemfile.lock
    libv8 (3.16.14.19)
    libv8 (3.16.14.19-x86_64-darwin-15)
    libv8 (3.16.14.19-x86_64-darwin-16)
    libv8 (3.16.14.19-x86_64-darwin-17)
      libv8 (~> 3.16.14.15)
>>> Testing bundler v2.2.9
Bundler version 2.2.9 (2021-02-08 commit 30e740c073)
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Writing lockfile to /private/tmp/bundler_issue/Gemfile.lock
    libv8 (3.16.14.19)
    libv8 (3.16.14.19-x86_64-darwin-15)
    libv8 (3.16.14.19-x86_64-darwin-16)
    libv8 (3.16.14.19-x86_64-darwin-17)
      libv8 (~> 3.16.14.15)
>>> Testing bundler v2.2.10
Bundler version 2.2.10 (2021-02-15 commit cc7c333721)
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Writing lockfile to /private/tmp/bundler_issue/Gemfile.lock
    libv8 (3.16.14.19)
    libv8 (3.16.14.19-x86_64-darwin-18)
      libv8 (~> 3.16.14.15)
>>> Testing bundler v2.2.11
Bundler version 2.2.11 (2021-02-17 commit 6ca677a0eb)
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Writing lockfile to /private/tmp/bundler_issue/Gemfile.lock
    libv8 (3.16.14.19)
    libv8 (3.16.14.19-x86_64-darwin-15)
    libv8 (3.16.14.19-x86_64-darwin-16)
    libv8 (3.16.14.19-x86_64-darwin-17)
      libv8 (~> 3.16.14.15)
```

so it looks like this is a bug present in the original implementation. 

Let me know if I can assist with any macOS-specific debugging

**Comment by owst** [comment]
I've just come across another similar example that _does_ work, given these starting Gemfile/Gemfile.lock files:
```
source 'https://rubygems.org'

gem 'sorbet', '= 0.5.6111'
```

```
GEM
  remote: https://rubygems.org/
  specs:
    sorbet (0.5.6111)
      sorbet-static (= 0.5.6111)
    sorbet-static (0.5.6111)

PLATFORMS
  ruby

DEPENDENCIES
  sorbet (= 0.5.6111)

BUNDLED WITH
   1.17.3
```
upgrade to bundler 2.2.11 with `bundle update --bundler`, and then add the platform (without version) specific specs with `bundle lock --add-platform x86_64-darwin`, which results in a `Gemfile.lock` diff of:
```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 53b1283..f0b954a 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -4,12 +4,20 @@ GEM
     sorbet (0.5.6111)
       sorbet-static (= 0.5.6111)
     sorbet-static (0.5.6111)
+    sorbet-static (0.5.6111-universal-darwin-14)
+    sorbet-static (0.5.6111-universal-darwin-15)
+    sorbet-static (0.5.6111-universal-darwin-16)
+    sorbet-static (0.5.6111-universal-darwin-17)
+    sorbet-static (0.5.6111-universal-darwin-18)
+    sorbet-static (0.5.6111-universal-darwin-19)
+    sorbet-static (0.5.6111-universal-darwin-20)
 
 PLATFORMS
   ruby
+  x86_64-darwin
 
 DEPENDENCIES
   sorbet (= 0.5.6111)
 
 BUNDLED WITH
-   1.17.3
+   2.2.11
```

n.b. that the `darwin-18` version _is_ added. Could it be something specific to `therubyracer` or `libv8` that causes the current platform version to not be added 🤔

**Comment by deivid-rodriguez** [comment]
Something weird with that version of `libv8` is that it includes invalid platform specific variants, like `libv8-3.16.14.19-x86-linux`, which by the way I just discovered is the result of mistyping `x86_64-linux` as `x86-64_linux`

```
> irb(main):002:0> Gem::Platform.new("x86-64_linux").to_s
=> "x86-linux"
```

But I can't imagine how that would end up causing this issue.

**Comment by PikachuEXE** [comment]
I got issue installing `libv8` with bundler 2.2 as well
I am able to reproduce my issue with docker:

#### Bundler 2.1 produced `Gemfile.lock` with Bundler 2.2
```bash
docker run --rm -it ruby:2.7 bash

bundler --version
touch Gemfile && echo 'source "https://rubygems.org"' > Gemfile
bundle add libv8
cat Gemfile.lock
gem update bundler && bundle update --bundler && bundler --version
cat Gemfile.lock
# Doesn't have to be `mini_racer` can be other normal gems
bundle add mini_racer
```

Content of produced `Gemfile.lock`
```
GEM
  remote: https://rubygems.org/
  specs:
    libv8 (8.4.255.0)

PLATFORMS
  ruby

DEPENDENCIES
  libv8 (~> 8.4)

BUNDLED WITH
   2.2.15
```

Using bundler 2.1 would install platform specific version
```
$ bundle add libv8
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.1.4
Fetching libv8 8.4.255.0 (x86_64-linux)
Installing libv8 8.4.255.0 (x86_64-linux)
```

Using bundler 2.2 would install from source
```
$ bundle add mini_racer
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.2.15
Fetching libv8 8.4.255.0
Installing libv8 8.4.255.0 with native extensions
```

#### Bundler 2.2 produced `Gemfile.lock` with Bundler 2.2
However bundler 2.2 is installing `libv8` platform specific version fine
With a `Gemfile.lock` produced by bundler 2.2
However that file now contains platform specific versions

```bash
docker run --rm -it ruby:2.7 bash

bundler --version
touch Gemfile && echo 'source "https://rubygems.org"' > Gemfile
gem update bundler && bundle update --bundler && bundler --version
bundle add libv8
cat Gemfile.lock
# Doesn't have to be `mini_racer` can be other normal gems
bundle add mini_racer
```

Content of produced `Gemfile.lock`
```
GEM
  remote: https://rubygems.org/
  specs:
    libv8 (8.4.255.0-x86_64-linux)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  libv8 (~> 8.4)

BUNDLED WITH
   2.2.15

```

**Comment by deivid-rodriguez** [comment]
@PikachuEXE What you explain is not related to this issue, but thanks for reporting it because it's a regression in 2.2.15, in particular from https://github.com/rubygems/rubygems/pull/4449. I'll fix it now!

**Comment by deivid-rodriguez** [comment]
Is this still reproducible?

**Comment by owst** [comment]
Hi @deivid-rodriguez - in short: yes. 

I've updated my Mac since I reported this, and now starting with:
```
$ gem env platform
ruby:x86_64-darwin-20
$ bundle --version
Bundler version 2.3.18
$ gem --version
3.3.18
```
starting with the original `Gemfile.lock` and running `bundle lock --add-platform x86_64-darwin` gives a diff of 
```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 96f6b0b..07e9403 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -2,6 +2,10 @@ GEM
   remote: https://rubygems.org/
   specs:
     libv8 (3.16.14.19)
+    libv8 (3.16.14.19-x86_64-darwin-15)
+    libv8 (3.16.14.19-x86_64-darwin-16)
+    libv8 (3.16.14.19-x86_64-darwin-17)
+    libv8 (3.16.14.19-x86_64-darwin-18)
     ref (2.0.0)
     therubyracer (0.12.3)
       libv8 (~> 3.16.14.15)
@@ -9,9 +13,10 @@ GEM

 PLATFORMS
   ruby
+  x86_64-darwin

 DEPENDENCIES
   therubyracer

 BUNDLED WITH
-   1.17.2
+   2.3.18
```
So against my original report it is now picking up `libv8 (3.16.14.19-x86_64-darwin-18)` but still not `libv8 (3.16.14.19-x86_64-darwin-19)` or `libv8 (3.16.14.19-x86_64-darwin-20)`

**Comment by deivid-rodriguez** [comment]
@owst That seems expected because there's no `libv8 (3.16.14.19-x86_64-darwin-19)` nor `libv8 (3.16.14.19-x86_64-darwin-20)`.

**Comment by owst** [comment]
🤦 Sorry @deivid-rodriguez you're right - I clearly wasn't paying attention, I think I read my diff/comment in https://github.com/rubygems/rubygems/issues/4370#issuecomment-780709228 and took the darwin versions from there without realising it was a different gem

Given that `libv8 (3.16.14.19-x86_64-darwin-18)` _is_ now added, I think the originally reported issue has been resolved - thank you!

**Comment by deivid-rodriguez** [comment]
Thanks @owst. I guess the situation is not exactly the same since now you're at darwin-20, not darwin-18 anymore. Anyways, I wrote a quick test simulating being on darwin-18 and everything including the darwin-18 variant was added to the lockfile. So whatever this was, I think it was fixed at some point.

In any case, let me know if something similar comes up in the future!
