### ISSUE TITLE
Using `http://rubygems.org` as the `allowed_push_host` makes `gem push` hang

### ISSUE THREAD

**Issue by analyticalCat** [rubygems/rubygems#4458]
I followed instructions on https://gist.github.com/jendiamond/6128723 to create a new gem.  When I tried to push it to rubygem.org, I used `bundle exec rake release` and got stuck on:

jz2021_helloworld 0.1.0 built to pkg/jz2021_helloworld-0.1.0.gem.
Tag v0.1.0 has already been created.
Pushing gem to http://rubygems.org...

Since it never says "pushed..." and I never saw the gem on rubygems.org, I assume the push was unsuccessful.  I checked past issues but couldn't find anything matched.  I would really appreciate it if you can provide some insight on what is happening on the Rubygems.org's side since there is no error message returned.

Please let me know if there is anything else I can provide.

Thanks in advance!

**Comment by deivid-rodriguez** [comment]
Could you tell us which versions of bundler & rubygems are you using? `gem -v` and `bundle -v` should show that.

**Comment by analyticalCat** [comment]
gem: 3.0.6
bundler: 2.1.4

Thank you so much!


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by deivid-rodriguez** [comment]
Can you try upgrading rubygems by running `gem update --system`?

**Comment by analyticalCat** [comment]
David,

I did, same error.

-Jess


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by deivid-rodriguez** [comment]
What does `bundle -v` and `gem -v` show after the upgrade?

**Comment by analyticalCat** [comment]
bundle 2.1.4
gem 3.2.14


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by deivid-rodriguez** [comment]
Run `bundle update --bundler` and try again.

**Comment by analyticalCat** [comment]
run bundle update --bundle

bunlde -v -> 2.2.14
gem -v -> 3.2.14

run bundle exec rake release again
same


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by deivid-rodriguez** [comment]
Sorry @analyticalCat, I don't know how to help you. Perhaps some readline issue? Are you on Windows?

**Comment by analyticalCat** [comment]
I am on mac.  No windows.

One strange thing I know is that the gemspec file asks for a CHANGLOG.md file but I don't think I have a file with such name.  Could that cause any problems?


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by deivid-rodriguez** [comment]
That sounds like it could be an issue, yeah. Can you show the error you're getting and which command you're running?

**Comment by analyticalCat** [comment]
That's the thing.  If I can see an error I will at least have some clue as of where to look.  I don't get an error by running "bundle exec rake release".  Below is copied from my command line:

~/code/create-gems/jz2021_helloworld$bundle exec rake release
jz2021_helloworld 0.1.0 built to pkg/jz2021_helloworld-0.1.0.gem.
Tag v0.1.0 has already been created.
Pushing gem to http://rubygems.org...

~/code/create-gems/jz2021_helloworld$



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by deivid-rodriguez** [comment]
Oh, sorry, I misunderstood your previous message about the gemspec asking for a CHANGELOG.md file and thought you were actually getting some error messages before the hang.

I think this is some readline issue when prompting for an OTP code. I assume you have OTP enabled on your rubygems.org account, right?

**Comment by analyticalCat** [comment]
Yes.

why would that make a difference?


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by deivid-rodriguez** [comment]
If you have `OTP` enabled, `bundler` will prompt for an `OTP` code before pushing. My hunch is that somehow `bundler` is prompting but the question is invisible (I think we had this issue a while ago but was fixed).

You can try using rubygems directly to workaround the issue for now, by pushing the `.gem` file directly through `gem push`.

**Comment by analyticalCat** [comment]
Sorry I keep bugging you.  It's still the same issue:

~/code/create-gems/jz2021_helloworld/pkg$gem push jz2021_helloworld-0.1.0.gem
Pushing gem to http://rubygems.org...

~/code/create-gems/jz2021_helloworld/pkg$


It did the same thing...


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by deivid-rodriguez** [comment]
No problem, not your fault. Does it work if you pass the otp code directly from the command line: `gem push jz2021_helloworld-0.1.0.gem --otp <code>`?

**Comment by analyticalCat** [comment]
Nope.  Exactly the same...


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by deivid-rodriguez** [comment]
What happens if you run the `gem push` command with `--backtrace` and `--verbose` flags, and you abort it with Ctrl-C after the hang. Do you get a backtrace?

**Comment by analyticalCat** [comment]
Here is what I have got:


Pushing gem to http://rubygems.org...

POST http://rubygems.org/api/v1/gems

307 Temporary Redirect



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by deivid-rodriguez** [comment]
Ok, that's a good clue. You seem to be using the insecure `http://rubygems.org` source, is that intentional? Can you post the result of `gem sources`?

**Comment by analyticalCat** [comment]
~/code/create-gems/jz2021_helloworld/pkg$gem sources

*** CURRENT SOURCES ***


https://rubygems.org/

It seems that I am using the https source.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by deivid-rodriguez** [comment]
I'm really confused, can you also post the gemspec of the gem you're trying to push?

**Comment by deivid-rodriguez** [comment]
Alright, I figured it out! The problem is here: https://github.com/analyticalCat/gem_helloworld/blob/41855108843cfd317d2329c6693663f87ea0a0fc/jz2021_helloworld.gemspec#L15. Remove that line and you should be good to go!

I'll leave this opened because hanging is not good. We should show a proper error.

**Comment by analyticalCat** [comment]
I pushed my first gem!

You are AMAZING!  Thank you for not giving up on me over such a long period of time!

Love it, love it, and love it!!!

-Jess


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by deivid-rodriguez** [comment]
Thank you @analyticalCat, I'm glad we figured this out!

I'll try to improve the experience so that new gem authors don't need to go through this :sweat_smile:.

**Comment by Mth0158** [comment]
Hi, 
I had the same problem, I commented out the line and it worked. Thank you @deivid-rodriguez for the solution!
![image](https://user-images.githubusercontent.com/74139731/121033561-98fdbc00-c7ac-11eb-8746-d8e212e60933.png)

I was doing it through Bundler tutorial (https://bundler.io/guides/creating_gem.html), it creates the whole gem structure, which is very nice, but it creates this line in the gemspec file: 
![image](https://user-images.githubusercontent.com/74139731/121034052-01e53400-c7ad-11eb-9de8-fc6eca9cfb26.png)
It would have been hard to figure on my own that this line was the one causing this error...

Thank you again!

**Comment by simi** [comment]
Would you mind to contribute to this guide at https://github.com/rubygems/bundler-site/blob/master/source/localizable/v2.2/guides/creating_gem.en.html.md to mention this step is needed?
