### ISSUE TITLE
unable to execute bundle plugin install diffend on bundler 2.2.22

### ISSUE THREAD

**Issue by nijikon** [rubygems/rubygems#4730]
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `/Users/n/.rbenv/versions/3.0.1/bin/bundle plugin install diffend`

- **What did you expect to happen?**

  I expected Bundler to install the plugin

## Backtrace

```
Bundler::URI::InvalidURIError: bad Bundler::URI(is not Bundler::URI?): "#<Gem::SourceList:0x00007ff2188a8b50>/"
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/vendor/uri/lib/uri/rfc3986_parser.rb:67:in `split'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/vendor/uri/lib/uri/rfc3986_parser.rb:73:in `parse'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/vendor/uri/lib/uri/common.rb:234:in `parse'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/vendor/uri/lib/uri/common.rb:737:in `URI'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/source/rubygems.rb:350:in `normalize_uri'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/source/rubygems.rb:247:in `add_remote'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/source_list.rb:68:in `add_global_rubygems_remote'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/plugin/installer.rb:80:in `install_all_sources'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/plugin/installer.rb:73:in `install_rubygems'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/plugin/installer.rb:25:in `install'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/plugin.rb:38:in `install'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/cli/plugin.rb:23:in `install'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:116:in `invoke'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor.rb:243:in `block in subcommand'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/cli.rb:30:in `dispatch'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/cli.rb:24:in `start'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/exe/bundle:49:in `block in <top (required)>'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
  /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/exe/bundle:37:in `<top (required)>'
  /Users/n/.rbenv/versions/3.0.1/bin/bundle:23:in `load'
  /Users/n/.rbenv/versions/3.0.1/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.2.22
  Platforms   ruby, x86_64-darwin-19
Ruby          3.0.1p64 (2021-04-05 revision 0fb782ee38ea37fd5fe8b1f775f8ad866a82a3f0) [x86_64-darwin19]
  Full Path   /Users/n/.rbenv/versions/3.0.1/bin/ruby
  Config Dir  /Users/n/.rbenv/versions/3.0.1/etc
RubyGems      3.2.15
  Gem Home    /Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0
  Gem Path    /Users/n/.gem/ruby/3.0.0:/Users/n/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0
  User Home   /Users/n
  User Path   /Users/n/.gem/ruby/3.0.0
  Bin Dir     /Users/n/.rbenv/versions/3.0.1/bin
Tools
  Git         2.32.0
  RVM         not installed
  rbenv       rbenv 1.1.2-61-g585ed84
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-07-06
Git SHA           0bdd3e8e71
Released Version  true
```

## Bundler settings

```
build.eventmachine
  Set for the current user (/Users/n/.bundle/config): "--with-cppflags=-I/usr/local/opt/openssl/include"
git.allow_insecure
  Set for the current user (/Users/n/.bundle/config): false
github.https
  Set for the current user (/Users/n/.bundle/config): "true"
path
  Set for your local app (/Users/n/dev/rb/karafka/avro/.bundle/config): "vendor/bundle"
  Set for the current user (/Users/n/.bundle/config): "vendor/bundle"
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

plugin 'diffend'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in karafka-avro-parser.gemspec
gemspec
```

### Gemfile.lock

```
PATH
  remote: .
  specs:
    karafka-avro-parser (0.2.0)
      avro_turf (~> 0.8)

GEM
  remote: https://rubygems.org/
  specs:
    avro (1.9.2)
      multi_json
    avro_turf (0.11.0)
      avro (>= 1.7.7, < 1.10)
      excon (~> 0.45)
    diff-lcs (1.4.4)
    excon (0.83.0)
    multi_json (1.15.0)
    rake (13.0.4)
    rspec (3.10.0)
      rspec-core (~> 3.10.0)
      rspec-expectations (~> 3.10.0)
      rspec-mocks (~> 3.10.0)
    rspec-core (3.10.1)
      rspec-support (~> 3.10.0)
    rspec-expectations (3.10.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-mocks (3.10.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-support (3.10.2)

PLATFORMS
  x86_64-darwin
  x86_64-darwin-19
  x86_64-linux

DEPENDENCIES
  bundler
  karafka-avro-parser!
  rake
  rspec

BUNDLED WITH
   2.2.22
```

### karafka-avro-parser.gemspec

```ruby
# frozen_string_literal: true

lib = File.expand_path('lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'karafka/parsers/avro/version'

Gem::Specification.new do |spec|
  spec.name          = 'karafka-avro-parser'
  spec.version       = Karafka::Parsers::Avro::VERSION
  spec.authors       = ['Kacper Madej']
  spec.email         = %w[kacperoza@gmail.com]
  spec.homepage      = 'https://github.com/karafka/avro'
  spec.summary       = 'Apache Avro support for Karafka'
  spec.description   = ''
  spec.license       = 'LGPL-3.0'

  spec.files         = `git ls-files -z`.split("\x0").reject do |f|
    # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
    f.match(%r{^(test|spec|features)/})
  end
  spec.require_paths = %w[lib]

  spec.required_ruby_version = '>= 2.6'

  spec.add_dependency 'avro_turf', '~> 0.8'

  spec.add_development_dependency 'bundler'
  spec.add_development_dependency 'rake'
  spec.add_development_dependency 'rspec'
end
```

**Comment by mensfeld** [comment]
Bypass:

```
bundle _2.2.22_ plugin install diffend --source https://rubygems.org
```

@nijikon can you check if that works?

**Comment by nijikon** [comment]
@mensfeld I can confirm that that workaround works.
```
balrog n$ bundle _2.2.22_ plugin install diffend --source https://rubygems.org
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.2.22
Fetching diffend 0.2.48
Installing diffend 0.2.48
Installed plugin diffend
```

**Comment by jaredbeck** [comment]
I can confirm that bundler 2.2.22 crashes, in my case with:

```
bundler plugin install bundler-why
Bundler::URI::InvalidURIError: bad Bundler::URI(is not Bundler::URI?): "#<Gem::SourceList:0x00007fa327058cd8>/"
```

Downgrading to 2.2.16 fixes the issue.

**Comment by mensfeld** [comment]
@jaredbeck this will work if you need:

```
bundle plugin install bundler-why --source https://rubygems.org
```

**Comment by deivid-rodriguez** [comment]
I'll propose a fix shortly. Apologies for the regression :pray:.

**Comment by deivid-rodriguez** [comment]
https://github.com/rubygems/rubygems/pull/4734 should fix this!

**Comment by nijikon** [comment]
@deivid-rodriguez I can confirm that #4734 fixes the issue.

**Comment by jaredbeck** [comment]
I'm still seeing this in 2.2.26. Perhaps 2.2.26 does not contain #4734 ?

**Comment by mensfeld** [comment]
@jaredbeck works for me:

```
bundle plugin install diffend
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.2.26
Fetching diffend 0.2.49
Installing diffend 0.2.49
Installed plugin diffend
```

though I spotted a different (maybe related) bug. When I retry the install procedure after a successful install, this is what happens:

```
bundle plugin install diffend
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.2.26
Using diffend 0.2.49
Failed to install the following plugins: `diffend`. The underlying error was: plugins.rb was not found in the plugin..
 /home/mencio/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler/plugin.rb:263:in `validate_plugin!'
 /home/mencio/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler/plugin.rb:249:in `block in save_plugins'
```

**Comment by deivid-rodriguez** [comment]
Oooops. But that issue has always been there?

**Comment by mensfeld** [comment]
@deivid-rodriguez no idea. I noticed that only now and since @jaredbeck reported that the base issue is back, I thought it may be related.

**Comment by deivid-rodriguez** [comment]
Thank you! I went back to 2.1.4 and the issue seems present in all versions, except for 2.2.22, where the issue reported in this ticket would happen instead. I will reticket this.
