### ISSUE TITLE
RubyGems version 3.3.3 is causing issues with Cocoapods

### ISSUE THREAD

**Issue by dibir-magomedsaygitov** [rubygems/rubygems#5235]
We are maintainers of [actions/virtual-environments](https://github.com/actions/virtual-environments) repository and we are having a problem with `Cocopapods` after `RubyGems` was updated to 3.3.3 version. Running command `pod --version` leads to an error messages, but also provides the version output at the end actually:
```
Error loading the plugin `cocoapods-deintegrate-1.0.5`.  NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x00007fd2ac80edb0> Did you mean?  activated? /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run' /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run' /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>' /usr/local/lib/ruby/gems/2.7.0/bin/pod:25:in `load' /usr/local/lib/ruby/gems/2.7.0/bin/pod:25:in `<main>' ---------------------------------------------   --------------------------------------------- Error loading the plugin `cocoapods-plugins-1.0.0`.  NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x00007fd2ac8179b0> Did you mean?  activated? /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run' /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run' /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>' /usr/local/lib/ruby/gems/2.7.0/bin/pod:25:in `load' /usr/local/lib/ruby/gems/2.7.0/bin/pod:25:in `<main>' ---------------------------------------------   --------------------------------------------- Error loading the plugin `cocoapods-search-1.0.1`.  NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x00007fd2ac815f48> Did you mean?  activated? /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run' /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run' /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>' /usr/local/lib/ruby/gems/2.7.0/bin/pod:25:in `load' /usr/local/lib/ruby/gems/2.7.0/bin/pod:25:in `<main>' ---------------------------------------------   --------------------------------------------- Error loading the plugin `cocoapods-trunk-1.6.0`.  NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x00007fd2ac80f1c0> Did you mean?  activated? /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run' /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run' /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>' /usr/local/lib/ruby/gems/2.7.0/bin/pod:25:in `load' /usr/local/lib/ruby/gems/2.7.0/bin/pod:25:in `<main>' ---------------------------------------------   --------------------------------------------- Error loading the plugin `cocoapods-try-1.2.0`.  NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x00007fd2ac80e8d8> Did you mean?  activated? /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each' /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run' /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run' /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>' /usr/local/lib/ruby/gems/2.7.0/bin/pod:25:in `load' /usr/local/lib/ruby/gems/2.7.0/bin/pod:25:in `<main>' ---------------------------------------------  1.11.2
```

Downgrading RubyGems version back to 3.2.33 resolves the issue.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env

RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.3
  - RUBY VERSION: 2.7.5 (2021-11-24 patchlevel 203) [x86_64-darwin20]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.7.0
  - USER INSTALLATION DIRECTORY: /Users/runner/.local/share/gem/ruby/2.7.0
  - RUBY EXECUTABLE: /usr/local/opt/ruby@2.7/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/lib/ruby/gems/2.7.0/bin
  - SPEC CACHE DIRECTORY: /Users/runner/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby@2.7/2.7.5/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-darwin-20
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.7.0
     - /Users/runner/.local/share/gem/ruby/2.7.0
     - /usr/local/Cellar/ruby@2.7/2.7.5/lib/ruby/gems/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/lib/ruby/gems/2.7.0/bin
     - /usr/local/opt/ruby@2.7/bin
     - /usr/local/opt/pipx_bin
     - /Users/runner/.cargo/bin
     - /usr/local/opt/curl/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /Users/runner/bin
     - /Users/runner/.yarn/bin
     - /Users/runner/Library/Android/sdk/tools
     - /Users/runner/Library/Android/sdk/platform-tools
     - /Users/runner/Library/Android/sdk/ndk-bundle
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/runner/.dotnet/tools
     - /Users/runner/.ghcup/bin
     - /Users/runner/hostedtoolcache/stack/2.7.3/x64
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Thank you for the report @dibir-magomedsaygitov, I can reproduce it. I'll have a look.

**Comment by deivid-rodriguez** [comment]
I bisected this to https://github.com/rubygems/rubygems/pull/5140/commits/ae3980eed01ed17c186ceb4094adef185864512e.

It is because `Gem.latest_specs` no longer returns `Gem::Specification` instances, but `Gem::StubSpecification` instances. Their interface is mostly the same, but `Gem::StubSpecification` instances cannot be activated directly without materializing them first into a `Gem::Specification`.

To fix the issue we could

* Define `activate` at `Gem::Specification` that first materializes the stub specification and then activates it.
* Restore `Gem::Specification.latest_specs` to behave as before, and define our own `Gem::Specification.latest_stubs` that does not materialize anything.
* Fix this at `CLaide`, the CocoaPods plugin manager where this issue is happening. CLaide is using too much RubyGems internals. If I understand correctly, it is completely reusing RubyGems plugin logic to define its own plugin system. This is not supported but it's not `CocoaPods` users fault that things work like that. Completely replacing it with custom logic seems too much work, but I don't think the plugin manager needs to activate specifications at all, since they are already activated anyways when `pod` is run.

I think I'll go with the second and third approaches above. The first is a bit simpler, but the second feels more bulletproof in case this affects other software.

**Comment by deivid-rodriguez** [comment]
Another option, given that this is just a warning a not a hard error, would be to fix this in `CLaide` only, and let users upgrade to get rid of the warning. As a matter of fact, provided that CocoaPods dependency on `CLaide` is flexible enough, users installing `CocoaPods` from scratch wouldn't need any changes since the latest (fixed) version of `CLaide` would be automatically picked up.

**Comment by mikehardy** [comment]
Cocoapods issue for cross reference https://github.com/CocoaPods/CocoaPods/issues/11134

**Comment by mikehardy** [comment]
Hello :wave: - I'm just pinning these issues together so they have visibility as everyone gets back to work after the winter holidays.
No intention to pressure, but I'm curious @deivid-rodriguez if you have any plans to do item 2 - "restore `Gem::Specification.latest_specs to behave as before` in the short term?

I checked up on your 3rd item (CLAide alterations) and it appears that the version range is loose, so I targeted fix there may be possible https://github.com/CocoaPods/CocoaPods/blob/f120f9fabda8bc7bea9995700e358ea22dd71cfe/Gemfile#L22

Although from a release management perspective simple reverts are pretty low effort in the short term even though they accrue a debt for future 

Anyway, just curious, cheers :-)

**Comment by deivid-rodriguez** [comment]
> Although from a release management perspective simple reverts are pretty low effort in the short term even though they accrue a debt for future

Yes, exactly. I would've never broken this intentionally. But since it has now happened, I want to figure out whether 3 is enough and we can move on without the revert.

**Comment by mikehardy** [comment]
I locally verified success with and posted workaround instructions on the cocoapods issue based on the downgrade recipe in your `UPGRADING.md` guide here, so people shouldn't get stuck if they bump their toe on this. If my ruby was worth anything I'd post a PR to CLAide but the time investment vs my value add in other areas is really prohibitive, and with a workaround for any affected folks in the meanwhile this doesn't seem "on fire" enough for me to take the hit so I'll let it sit personally, with apologies. Thanks David

**Comment by mikehardy** [comment]
I should mention that the current version of CLAide does not appear to work for me in fresh installs where the cocoapods needed for a build are not already present locally on the machine, so it appears to be a break not just a warning for cocoapods (though if they're using internals, who is responsible right? CLAide I'd assert, though it's still a break for users). 

Anyway, cocoapods has a verified temporary workaround, which should move it from "important and urgent" to just "important" which is always nice

**Comment by deivid-rodriguez** [comment]
Yes, this is indeed a break. It's a warning for `pod --version` since it doesn't use plugins, but with this issue plugins are not actually loaded properly so I guess that must break something 😅.

**Comment by deivid-rodriguez** [comment]
Alright, since a new `CLAide` version has been released that should fix this particular problem, I'll close this for now. If new issues arise on different libraries that point to the same culprit, I'll reconsider again to fix this ourselves.

**Comment by dibir-magomedsaygitov** [comment]
Hello @deivid-rodriguez. Unfortunately, we are still experiencing the same issue.

**Comment by mikehardy** [comment]
Triple check your local environment, I have personally experienced success with the fix in CLAide and it is confirmed working just now by another user. The fix should be good, but it's not easy to perfectly isolate + troubleshoot + fix local environments all the time.

**Comment by deivid-rodriguez** [comment]
Yes, make sure you're using the new CLAide version. if you're getting the exact same error, you're definitely not using the new version because I slightly changed the error message.

**Comment by dibir-magomedsaygitov** [comment]
Hello @deivid-rodriguez and @mikehardy. We are observing the same error message even with the latest version of CLAide on the image. Could you please take a look at the issue one more time.

**Comment by deivid-rodriguez** [comment]
Please do some research yourself. As I stated above, if you're getting the exact same error, that certainly means you're still using the old CLAide version.

**Comment by mikehardy** [comment]
> Yes, make sure you're using the new CLAide version. if you're getting the exact same error, you're definitely not using the new version because I slightly changed the error message.

That was quite clever, the errormessage change. Going to have to remember that strategy for the future myself to help offer certainty in situations like this.
