### ISSUE TITLE
https://rubygems.org/ - SSL_connect B: certificate verify failed

### ISSUE THREAD

**Issue by emeyekayee** [rubygems/rubygems#665]
gem install pry
ERROR:  Could not find a valid gem 'pry' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://s3.amazonaws.com/production.s3.rubygems.org/latest_specs.4.8.gz)

**Comment by martialdidit** [comment]
:+1: @danj3 works on Windows 7 64bits

**Comment by jfloff** [comment]
:+1:  @danj3 @fifahuihua

**Comment by WattyRev** [comment]
@vchervanev That solved the issue for me.

**Comment by webdevilopers** [comment]
:+1: for the solution provided by @fifahuihua:
```
gem sources -a http://rubygems.org
```

Now works on `Windows 7 Ultimate` and `rubyinstaller-2.1.5` on 64bit.

**Comment by descifixer16** [comment]
@danj3 you're solution works fine ! ! ! ( Windows 7 Ultimate with railsinstaller-3.1.0 ) 
same with webdevilopers,, api solution is not working too!

**Comment by drbrain** [comment]
@fifahuihua @webdevilopers switching the source to `http://rubygems.org` allows an attacker to install malicious gems.  Use this guide to fix it properly: https://gist.github.com/luislavena/f064211759ee0f806c88

**Comment by matias89** [comment]
Perfect! Thanks!

**Comment by Jemma5** [comment]
Hey there, I had the same problem. Put next line code into: Start Command Prompt with Ruby
gem sources -a http://rubygems.org
it will come up with a "Do you want to add this insecure source? [yn] 
Put 'y' for yes
then put 
gem install pry

**Comment by princeofstar** [comment]
guys, i figured how to fix this problem.
Check this out.

ERROR:  Could not find a valid gem 'sass' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ no such name (
https://rubygems.org/specs.4.8.gz)

1. go this website, download latest sass file 
https://rubygems.org/gems/sass

2. create new folder on C drive, name `SASS` file. 

3. back to the command prompt 
cd C:¥SASS
gem install sass

I hope you will be succeed.

**Comment by ccoenen** [comment]
@princeofstar you're installing a sass you downloaded to your harddrive. That is a workaround, but you will probably be better of by updating your rubygems in the long run.

This link contains the howto: "[Installing using update packages (NEW)](https://gist.github.com/luislavena/f064211759ee0f806c88#installing-using-update-packages-new)". Basically, you do the same thing you did with sass, but instead with rubygems itself. This will fix the problem for all future gems.

**Comment by anandasansol** [comment]
I am getting this error:
ERROR:  Could not find a valid gem 'sass' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect retur
ned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (
https://api.rubygems.org/latest_specs.4.8.gz)
Any workaround?

**Comment by ccoenen** [comment]
@anandasansol: yes, plenty. The short advice is to install a more up-to-date version of rubygems itself. Please have a look at the post directly before your post. It contains a link to the solution. If there's something weird happening, please let us know!

**Comment by steveharville** [comment]
@Jemma5 - your solution worked for me on 2.2.2 . Thanks!

**Comment by ccoenen** [comment]
@steveharville it should be noted that this is not a good idea. As indicated by the warning you get from following that workaround. It's a temporary help, at best!

# Public service announcement for everyone wanting a Solution

There's **one** solution to this problem, and it's **updating your rubygems**. Everything else is just a workaround. Please follow the instructions by @luislavena, described in detail here: https://gist.github.com/luislavena/f064211759ee0f806c88#installing-using-update-packages-new

Please don't use the other workarounds, especially not those, that favor insecure HTTP connections.

**Comment by danj3** [comment]
The reason people are going for the bad/easy solution is because the right solution is not as easy as it should be, i.e. cut and paste.

If you have 2.x>, this fancy automatic solution should(might) work for unix/osx:

ruby -ruri -ropen-uri -e 'v={"2.2"=>"2.2.3","2.0"=>"2.0.15","1.8"=>"1.8.30"}[Gem::VERSION.split(".")[0..1].join(".")];uri=URI.parse("https://github.com/rubygems/rubygems/releases/download/v#{v}/rubygems-update-#{v}.gem <https://github.com/rubygems/rubygems/releases/download/v#{v}/rubygems-update-#{v}.gem>");File.write("/tmp/rubygems-update.gem",uri.read)'; gem install --local /tmp/rubygems-update.gem; update_rubygems --no-ri --no-rdoc; rm /tmp/rubygems-update.gem

The 1.8.x version would be:

curl https://github.com/rubygems/rubygems/releases/download/v1.8.30/rubygems-update-1.8.30.gem <https://github.com/rubygems/rubygems/releases/download/v1.8.30/rubygems-update-1.8.30.gem> > /tmp/rubygems-update.gem; gem install --local /tmp/rubygems-update.gem; update_rubygems --no-ri --no-rdoc; rm /tmp/rubygems-update.gem

The other versions, broken out are:

2.2.x:

curl https://github.com/rubygems/rubygems/releases/download/v2.2.3/rubygems-update-2.2.3.gem > /tmp/rubygems-update.gem; gem install --local /tmp/rubygems-update.gem; update_rubygems --no-ri --no-rdoc; rm /tmp/rubygems-update.gem

2.0.x
curl https://github.com/rubygems/rubygems/releases/download/v2.0.15/rubygems-update-2.0.15.gem > /tmp/rubygems-update.gem; gem install --local /tmp/rubygems-update.gem; update_rubygems --no-ri --no-rdoc; rm /tmp/rubygems-update.gem


After all that, if you made the http (bad) fix, do this:

gem sources --add https://rubygems.org <https://rubygems.org/>
gem sources --remove http://rubygems.org <http://rubygems.org/>

Unless there's a bug/typo in the above, this should put the whole problem to rest. Best of luck.

Dan

**Comment by ShlomiHasin** [comment]
Thank you.

**Comment by collins001** [comment]
C:\DevKit>gem install json --platform=ruby
ERROR:  Could not find a valid gem 'json' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNABORT
ED: An established connection was aborted by the software in your host machine.
- SSL_connect (https://api.rubygems.org/specs.4.8.gz)

**Comment by collins001** [comment]
Mine issue is a bit different...
Can anyone help with an answer on how to resolve this error.:
C:\DevKit>gem install json --platform=ruby
ERROR: Could not find a valid gem 'json' (>= 0), here is why:
Unable to download data from https://rubygems.org/ - Errno::ECONNABORT
ED: An established connection was aborted by the software in your host machine.

    SSL_connect (https://api.rubygems.org/specs.4.8.gz)

**Comment by drbrain** [comment]
@collins001 what RubyGems version are you using?  If ruby is trying to download `specs.4.8` you likely have an out-of-date version which does not have the correct CA certificates to securely connect to RubyGems.org.

**Comment by 3686** [comment]
Updating system gems worked for me:
```
gem update --system
```

**Comment by vtanathip** [comment]
I still have the problem with gem.

this is a fresh install ruby version 2.2.5p319 from http://rubyinstaller.org/

> Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

![image](https://cloud.githubusercontent.com/assets/624619/19209493/805b7608-8d35-11e6-8fbb-6cf0a7ca8bb5.png)

ruby version 2.2.5p319
gem version 2.4.5.1
OS: window 7 64bit

Have anyone an idea to solve this?
Thanks you in advance.

**Comment by Fire-Dragon-DoL** [comment]
Having this problem too. Wonder what's the cause. I noticed api.rubygems.org has a "too many redirects" error

**Comment by vtanathip** [comment]
@RupW  Thanks, that's help!!!

Have to say that document resolved my issues. :+1:  

Hope someone that have the same problem will resolve it.

FYI: I use MANUAL SOLUTION TO SSL ISSUE

**Comment by Fire-Dragon-DoL** [comment]
I fixed mine by manually installing rubygems and upgrading openssl on osx yosemite

**Comment by rishifactual** [comment]
Neither @RupW or @Fire-Dragon-DoL 's suggestions worked for me (OSX Yosemite 10.10.5). RubyGems version 2.6.7. Still getting the same error message. Does anyone have other suggestions?

**Comment by Fire-Dragon-DoL** [comment]
@rishifactual As someone pointed out, it's a problem with RVM rubies, they are built with old openssl. Update openssl, reinstall your ruby with `rvm install 2.3.1 --disable-binary`, which will force a recompile instead of using rvm binaries. This should address the issue.

**Comment by rishifactual** [comment]
perfect! Thanks

**Comment by Fire-Dragon-DoL** [comment]
https://github.com/rubygems/rubygems/issues/1745

**Comment by jrvaghela72** [comment]
http://stackoverflow.com/a/28803395/4844439

**Comment by Fire-Dragon-DoL** [comment]
That's **not** a solution, you are trading security (a big one) if you use `http` instead of `https`, please regret from even recommending that.

**Comment by drbrain** [comment]
@Fire-Dragon-DoL I redacted it here and flagged it on stack overflow

**Comment by Fire-Dragon-DoL** [comment]
Thanks @drbrain !

**Comment by officialmmt** [comment]
Fix is here `http://guides.rubygems.org/ssl-certificate-update/#background`

**Comment by Fire-Dragon-DoL** [comment]
@officialmmt nope, I applied that fix and didn't work, the only fix currently was recompiling the rubies

**Comment by trajano** [comment]
@officialmmt slight alteration for your instructions.  I copied the global.pem then I made sure I remove all sources using 

`gem source --list`
`gem source --remove ...`

Finally I added back rubygems.org

`gem source --add https://rubygems.org/`

**Comment by gabeodess** [comment]
I had to reinstall openssl:

```
brew uninstall --force openssl
brew install openssl
```

**Comment by felixfbecker** [comment]
I am still getting this error with a fresh install on windows

**Comment by vnluc** [comment]
I got this error also. The cause is gem is updated and also the certificates.

Please follow this guide to update gem & the certificates, it helped me out.

http://guides.rubygems.org/ssl-certificate-update/

**Comment by vchinthakunta** [comment]
This solution did not work for me..If you are facing the same.. try the steps from https://gist.github.com/eyecatchup/20a494dff3094059d71d
Worked for me!!

**Comment by omidheshmatinia** [comment]
I just removed the https url and replace it with http one.

gem sources --remove https://rubygems.org/
gem sources --add http://rubygems.org/

**Comment by vnluc** [comment]
@omidheshmatinia: This is in secure way, better follow my way if it works. Or ccoenen is ok also.

**Comment by ccoenen** [comment]
I flag this answer whenever I see it on Stack Overflow, but the moderators there usually don't agree with my assessment that a dangerous way should not be on that site. It appears to be quite hard to understand that YOU ARE F*CKING OPEN TO ALL KINDS OF ATTACKS if you miss that tiny little **s** in your gem sources.

**Comment by fguillen** [comment]
In my case:

- OSX 0.12.6
- Ruby 2.0.0-p247
- rbenv 1.1.1-28-gb943955

Updating Ruby to 2.4.2 made the trick.

**Comment by ain** [comment]
Reinstalling Ruby worked for me:

1. `rvm uninstall 2.7.1`
2. `rvm install 2.7.1`
