### ISSUE TITLE
When using JRuby 9.4.7 and bundler 2.5.11, Adding additional platforms to the lockfile removes existing ones 

### ISSUE THREAD

**Issue by skunkworker** [rubygems/rubygems#7741]
I originally posted this issue in https://github.com/jruby/jruby/issues/8287 but was told this is unlikely to be a JRuby bug.

### Environment Information

jruby-9.4.7.0 @ jdk21
cruby-3.1.5
macOS 14.5
bundler 2.5.11

### Describe the problem as clearly as you can

When using JRuby 9.4.7 (latest) , I cannot add additional platforms to the `Gemfile.lock` without existing platforms being removed.
However, with CRuby 3.1.5 this does not occur and I am able to add additional platforms without removal.

### Post steps to reproduce the problem
I start with the following `PLATFORMS` section in my Gemfile.
```
PLATFORMS
   arm64-darwin-22
   arm64-darwin-23
   universal-java-17
   x86_64-linux
```

And run
```
bundle lock --add-platform arm64-darwin-22 arm64-darwin-23 x86_64-linux universal-java-17 universal-java-21
```
I expect just the `universal-java-21` platform to be added to the Gemfile.lock.

### Which command did you run?

`bundle lock --add-platform arm64-darwin-22 arm64-darwin-23 x86_64-linux universal-java-17 universal-java-21`

### What were you expecting to happen?

```
PLATFORMS
   arm64-darwin-22
   arm64-darwin-23
   universal-java-17
+  universal-java-21
   x86_64-linux
```

### What actually happened?

```
PLATFORMS
-  arm64-darwin-22
-  arm64-darwin-23
   universal-java-17
-  x86_64-linux
+  universal-java-21
```

## Environment

```
Bundler             2.5.9
  Platforms         ruby, universal-java-17
Ruby                3.1.4p0 (2024-04-29 revision 597ff08ac1e0d7f05f8f6cc836648725756dd7db) [universal-java-17]
  Full Path         /Users/john/.rvm/rubies/jruby-9.4.7.0/bin/jruby
  Config Dir        /Users/john/.rvm/rubies/jruby-9.4.7.0/etc
RubyGems            3.5.11
  Gem Home          /Users/john/.rvm/gems/jruby-9.4.7.0
  Gem Path          /Users/john/.rvm/gems/jruby-9.4.7.0:/Users/john/.rvm/rubies/jruby-9.4.7.0/lib/ruby/gems/shared
  User Home         /Users/john
  User Path         /Users/john/.gem/jruby/3.1.0
  Bin Dir           /Users/john/.rvm/gems/jruby-9.4.7.0/bin
Tools
  Git               2.45.0
  RVM               1.29.12-next (master)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2024-04-12
Git SHA           4304697e0c
Released Version  true
```

## Bundler settings

```
build.nokogiri
  Set for the current user (/Users/john/.bundle/config): "--use-system-libraries"
cache_all
  Set for your local app (/Users/john/dev/myapp/.bundle/config): false
cache_all_platforms
  Set for the current user (/Users/john/.bundle/config): true
deployment
  Set for your local app (/Users/john/dev/myapp/.bundle/config): false
gem.changelog
  Set for the current user (/Users/john/.bundle/config): true
gem.ci
  Set for the current user (/Users/john/.bundle/config): "gitlab"
gem.coc
  Set for the current user (/Users/john/.bundle/config): false
gem.linter
  Set for the current user (/Users/john/.bundle/config): "rubocop"
gem.mit
  Set for the current user (/Users/john/.bundle/config): true
gem.push_key
  Set for the current user (/Users/john/.bundle/config): "[REDACTED]"
gem.test
  Set for the current user (/Users/john/.bundle/config): "rspec"
jobs
  Set for the current user (/Users/john/.bundle/config): 8

**Comment by deivid-rodriguez** [comment]
Thanks for the report!

In the issue title, it mentions Bundler 2.5.11, however your `bundle env` shows you're using 2.5.9. Can you rerun with Bundler 2.5.11 and post updated information?

Also, would it be possible to share a Gemfile that reproduces the problem? I understand you're most likely using private gems, but can you try minimize the Gemfile removing the private stuff and see if the problem still reproduces? I did some testing with JRuby and I was not able to reproduce the problem, that's why I need more specific information.

**Comment by deivid-rodriguez** [comment]
I'll close since there was no further feedback, so assuming this was fixed in the latest releases. If you're still running into this, please reopen posting the requested information if possible.

**Comment by skunkworker** [comment]
@deivid-rodriguez I just tried with bundler `2.5.14` on jruby-9.4.7 and this issue still occurred. The platforms were removed from the `gemfile.lock` upon `bundler update`

**Comment by deivid-rodriguez** [comment]
Ok, thanks. I'll reopen for a couple more weeks in case someone else posts the requested information. Otherwise this issue is not actionable for me, since I don't know what's wrong and I can't reproduce the problem.

**Comment by skunkworker** [comment]
@deivid-rodriguez I'm currently in the process of creating a reproducible example. I unfortunately cannot share the original Gemfile since it contains internal gems hosted on a JFrog rubygems pull through mirror (one of the areas I'm considering there might be a problem). 

But as of right now I've narrowed it down to some oddities around an internal gem that we publish two versions of, one with no platform specified and the other `java`, and also having a `platforms:` block.

The frustrating thing so far is that it doesn't occur every time, just some of the time. Is there a verbose flag I could enable, that would print when a platform _gets removed from the lockfile?_.

**Comment by deivid-rodriguez** [comment]
Thanks! No, but I'll try to introduce some debug logging for this and let you know once ready so you can get more information that may help you isolate this more 👍.

**Comment by deivid-rodriguez** [comment]
I still did not add debug logging but improvements have been reported here. Can you check if the problem still reproduces on Bundler 2.5.16?

**Comment by KostyaSha** [comment]
> I still did not add debug logging but improvements have been reported here. Can you check if the problem still reproduces on Bundler 2.5.16?

<img width="285" alt="Screenshot 2024-08-02 at 15 42 36" src="https://github.com/user-attachments/assets/dbce1a0a-ee07-47cd-927a-432c9b3d2cf2">

I see that indent changed 

<img width="341" alt="Screenshot 2024-08-02 at 15 41 04" src="https://github.com/user-attachments/assets/328043e9-a44a-4986-9a47-e1f0ac35e2dc">

**Comment by KostyaSha** [comment]
looks like... i dont' remember i ever touched them manually... sorry if it's unrelated

**Comment by deivid-rodriguez** [comment]
Sometimes Bundler will remove "ruby" and replace it with the current more specific platform, because the current lockfile is not valid for the generic "ruby" platform. That's generally necessary because at some point Bundler used "ruby" for cases where "ruby" is not really valid (for example, [sorbet-static](https://rubygems.org/gems/sorbet-static/versions) only ships platform specific variants, so it's not valid for the generic "ruby" platform).

Let's tackle one issue at a time though, I'll try to improve how we handle inconsistent indentations.

**Comment by deivid-rodriguez** [comment]
I proposed a fix for this at #7916.
